-- Fix vendor_library table columns and add comprehensive resource enhancement
-- First, add missing columns to vendor_library table if they don't exist

-- Add missing columns to vendor_library table
ALTER TABLE vendor_library 
ADD COLUMN IF NOT EXISTS deployment_scenarios jsonb DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS configuration_complexity text DEFAULT 'medium',
ADD COLUMN IF NOT EXISTS documentation_quality text DEFAULT 'good',
ADD COLUMN IF NOT EXISTS market_presence text DEFAULT 'established',
ADD COLUMN IF NOT EXISTS typical_use_cases jsonb DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS integration_notes text,
ADD COLUMN IF NOT EXISTS model_series jsonb DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS firmware_versions jsonb DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS key_features jsonb DEFAULT '[]'::jsonb;

-- Now proceed with the comprehensive vendor additions using existing table structure
INSERT INTO vendor_library (vendor_name, category, portnox_integration_level, supported_protocols, deployment_scenarios, configuration_complexity, documentation_quality, support_rating, market_presence, typical_use_cases, integration_notes, model_series, firmware_versions, key_features, created_by) VALUES

-- Cisco Comprehensive
('Cisco Enterprise', 'wired', 'native', '["802.1X", "MAB", "WebAuth", "RADIUS", "TACACS+", "ISE Integration"]', '["Enterprise", "Campus", "Branch", "Data Center", "Cloud"]', 'high', 'excellent', 5.0, 'enterprise_leader', '["Enterprise Campus", "Branch Office", "Data Center", "Healthcare", "Education", "Government", "Manufacturing"]', 'Full ISE integration with dynamic VLAN assignment, profiling, and posture assessment', '["Catalyst 9000", "Catalyst 3850", "Catalyst 3650", "Catalyst 2960-X", "Catalyst 2960-L", "Nexus 9000", "Nexus 7000", "ASR 9000", "ISR 4000", "Meraki MS"]', '["IOS-XE 16.x", "IOS-XE 17.x", "NX-OS 9.x", "NX-OS 10.x"]', '["TrustSec", "MACsec", "Dynamic VLAN", "Voice VLAN", "PoE+", "mGig", "Stack-Wise"]', (SELECT id FROM profiles WHERE email = 'system@portnox.com' LIMIT 1)),

-- Aruba Comprehensive  
('Aruba Networks', 'wired', 'certified', '["802.1X", "MAB", "WebAuth", "RADIUS", "TACACS+", "ClearPass Integration"]', '["Enterprise", "Campus", "Branch", "Hospitality", "Healthcare"]', 'high', 'excellent', 4.8, 'enterprise_leader', '["Enterprise Campus", "Hospitality", "Healthcare", "Education", "Retail", "Manufacturing"]', 'Deep integration with ClearPass for policy enforcement and device profiling', '["2930F", "2930M", "3810M", "5400R", "6200F", "6300F", "6400", "8320", "8325", "CX 6000"]', '["ArubaOS-Switch 16.x", "ArubaOS-CX 10.x"]', '["VSF", "ARP Protection", "DHCP Snooping", "Dynamic Segmentation", "Zero Touch Provisioning"]', (SELECT id FROM profiles WHERE email = 'system@portnox.com' LIMIT 1)),

-- Juniper Comprehensive
('Juniper Networks', 'wired', 'certified', '["802.1X", "MAB", "WebAuth", "RADIUS", "TACACS+"]', '["Enterprise", "Campus", "Service Provider", "Data Center"]', 'high', 'excellent', 4.7, 'enterprise_leader', '["Enterprise Campus", "Service Provider", "Data Center", "Cloud Provider"]', 'Strong JUNOS integration with advanced security features', '["EX2300", "EX3400", "EX4300", "EX4600", "EX9200", "QFX5100", "QFX10000", "MX Series"]', '["Junos 18.x", "Junos 19.x", "Junos 20.x", "Junos 21.x"]', '["Virtual Chassis", "EVPN-VXLAN", "MACsec", "Pulse Secure Integration", "SRX Integration"]', (SELECT id FROM profiles WHERE email = 'system@portnox.com' LIMIT 1)),

-- Microsoft Azure AD
('Microsoft Entra ID', 'idp', 'native', '["SAML 2.0", "OAuth 2.0", "OpenID Connect", "WS-Fed", "RADIUS", "LDAP"]', '["Cloud", "Hybrid", "Enterprise", "M365"]', 'medium', 'excellent', 4.8, 'enterprise_leader', '["Microsoft 365", "Enterprise", "Hybrid Cloud", "Government"]', 'Complete identity platform with conditional access and MFA', '["Azure AD Free", "Azure AD Premium P1", "Azure AD Premium P2", "Entra ID"]', '["Current", "Preview"]', '["Conditional Access", "MFA", "PIM", "Identity Protection", "Single Sign-On", "B2B/B2C"]', (SELECT id FROM profiles WHERE email = 'system@portnox.com' LIMIT 1)),

-- Okta
('Okta Identity Cloud', 'idp', 'native', '["SAML 2.0", "OAuth 2.0", "OpenID Connect", "RADIUS", "LDAP", "SCIM"]', '["Cloud", "SaaS", "Enterprise", "Multi-cloud"]', 'medium', 'excellent', 4.7, 'cloud_leader', '["SaaS Applications", "Cloud-first Enterprise", "Multi-cloud", "Identity Governance"]', 'Cloud-native identity platform with extensive app catalog', '["Workforce Identity", "Customer Identity", "Privileged Access"]', '["Current Production"]', '["Universal Directory", "Lifecycle Management", "Adaptive MFA", "API Access Management"]', (SELECT id FROM profiles WHERE email = 'system@portnox.com' LIMIT 1)),

-- Microsoft Intune
('Microsoft Intune', 'mdm', 'native', '["MDM", "MAM", "Certificate Deployment", "Wi-Fi Profiles", "VPN Profiles"]', '["Enterprise", "M365", "Hybrid", "Cloud"]', 'medium', 'excellent', 4.7, 'enterprise_leader', '["Microsoft 365 Enterprise", "Windows Environment", "Hybrid Cloud"]', 'Native integration with Azure AD for certificate-based authentication', '["Microsoft Intune"]', '["Current Service"]', '["Conditional Access", "Compliance Policies", "App Protection", "Certificate Management", "Co-management"]', (SELECT id FROM profiles WHERE email = 'system@portnox.com' LIMIT 1)),

-- Cisco Wireless
('Cisco Wireless Systems', 'wireless', 'native', '["802.1X", "MAB", "WebAuth", "RADIUS", "WPA3", "OWE", "SAE"]', '["Enterprise", "Campus", "Branch", "Outdoor", "Industrial"]', 'high', 'excellent', 5.0, 'enterprise_leader', '["Enterprise Campus", "Branch Office", "Outdoor Coverage", "High Density", "Healthcare", "Education"]', 'Full integration with ISE and DNA Center for advanced analytics', '["Catalyst 9100", "Catalyst 9105", "Catalyst 9115", "Catalyst 9117", "Catalyst 9120", "Catalyst 9130", "Aironet 1800", "Aironet 2800", "Aironet 3800", "Aironet 4800", "Meraki MR"]', '["IOS-XE 17.x", "Meraki 28.x", "Meraki 29.x"]', '["Wi-Fi 6E", "Wi-Fi 7", "ClientLink", "BandSelect", "CleanAir", "Hyperlocation", "mGig", "802.11ax"]', (SELECT id FROM profiles WHERE email = 'system@portnox.com' LIMIT 1)),

-- Aruba Wireless
('Aruba Wireless', 'wireless', 'certified', '["802.1X", "MAB", "WebAuth", "RADIUS", "WPA3", "OWE", "SAE"]', '["Enterprise", "Campus", "Branch", "Outdoor", "Hospitality"]', 'high', 'excellent', 4.9, 'enterprise_leader', '["Enterprise Campus", "Hospitality", "Healthcare", "Education", "Retail", "Manufacturing"]', 'Deep ClearPass integration with AI-powered RF optimization', '["AP-515", "AP-535", "AP-555", "AP-575", "AP-635", "AP-655", "AP-665", "AP-715", "IAP-515", "IAP-535"]', '["ArubaOS 8.10.x", "ArubaOS 8.11.x", "Instant 8.10.x"]', '["Wi-Fi 6E", "AI-powered RF", "ClientMatch", "AirMatch", "AppRF", "Spectrum Analysis"]', (SELECT id FROM profiles WHERE email = 'system@portnox.com' LIMIT 1)),

-- SaaS Applications
('Microsoft Office 365', 'saas_app', 'native', '["SAML 2.0", "OAuth 2.0", "OpenID Connect", "WS-Federation"]', '["Cloud", "Hybrid", "Enterprise", "Remote Work"]', 'medium', 'excellent', 4.9, 'enterprise_leader', '["Office Productivity", "Email", "Collaboration", "File Sharing", "Teams"]', 'Native Azure AD integration with conditional access and Zero Trust', '["Office 365", "Microsoft 365", "Enterprise Mobility + Security"]', '["Current Channel", "Monthly Channel", "Semi-Annual Channel"]', '["Conditional Access", "Azure AD SSO", "MFA Integration", "App Protection Policies", "Compliance Center"]', (SELECT id FROM profiles WHERE email = 'system@portnox.com' LIMIT 1)),

('Salesforce CRM', 'saas_app', 'certified', '["SAML 2.0", "OAuth 2.0", "OpenID Connect"]', '["Cloud CRM", "Sales Automation", "Customer Service", "Marketing"]', 'medium', 'excellent', 4.8, 'crm_leader', '["CRM", "Sales Automation", "Customer Service", "Marketing Automation", "Analytics"]', 'Comprehensive SAML SSO with custom attributes and JIT provisioning', '["Sales Cloud", "Service Cloud", "Marketing Cloud", "Commerce Cloud", "Platform"]', '["Spring Release", "Summer Release", "Winter Release"]', '["SAML SSO", "Just-in-Time Provisioning", "Custom Attributes", "Lightning Platform", "Salesforce Identity"]', (SELECT id FROM profiles WHERE email = 'system@portnox.com' LIMIT 1));

-- Add device types to device_library
INSERT INTO device_library (device_name, category, authentication_methods, typical_use_cases, deployment_considerations, security_implications, vendor_examples, configuration_complexity, market_presence, integration_notes, network_behavior, power_requirements, form_factors, created_by) VALUES

-- Computing Devices
('Windows Enterprise Laptop', 'endpoint', '["802.1X-EAP-TLS", "802.1X-PEAP", "802.1X-EAP-TTLS", "Machine Auth", "User Auth"]', '["Corporate Users", "Remote Work", "BYOD", "Contractors"]', '["Certificate Deployment", "GPO Configuration", "MDM Enrollment", "Compliance Checks"]', '["Domain Join Required", "BitLocker Encryption", "Windows Defender", "Patch Management"]', '["Dell Latitude", "HP EliteBook", "Lenovo ThinkPad", "Microsoft Surface"]', 'medium', 'enterprise_standard', 'Excellent support for machine and user authentication with certificate auto-enrollment', '["DHCP Client", "DNS Registration", "Domain Authentication", "Software Updates"]', 'Battery/AC Power', '["Laptop", "2-in-1", "Ultrabook"]', (SELECT id FROM profiles WHERE email = 'system@portnox.com' LIMIT 1)),

('MacBook Pro/Air', 'endpoint', '["802.1X-EAP-TLS", "802.1X-PEAP", "802.1X-EAP-TTLS", "User Auth"]', '["Creative Professionals", "Executives", "BYOD", "Education"]', '["Profile Deployment", "Jamf Management", "Certificate Distribution", "User Training"]', '["FileVault Encryption", "Gatekeeper", "XProtect", "MDM Enrollment"]', '["MacBook Air", "MacBook Pro", "iMac", "Mac Studio"]', 'medium', 'creative_standard', 'Strong certificate support through profiles and keychain integration', '["Bonjour Discovery", "DHCP Client", "Time Machine", "Software Updates"]', 'Battery/AC Power', '["Laptop", "Desktop", "All-in-One"]', (SELECT id FROM profiles WHERE email = 'system@portnox.com' LIMIT 1)),

-- Mobile Devices
('iPhone Enterprise', 'mobile', '["802.1X-EAP-TLS", "802.1X-PEAP", "802.1X-EAP-TTLS", "Certificate-based"]', '["Corporate Mobile", "BYOD", "Executive Devices", "Field Workers"]', '["MDM Enrollment", "Profile Installation", "App Store Management", "VPN Configuration"]', '["Device Encryption", "Passcode Policies", "Remote Wipe", "App Sandboxing"]', '["iPhone 13", "iPhone 14", "iPhone 15", "iPhone SE"]', 'low', 'consumer_enterprise', 'Excellent enterprise features with strong certificate support via MDM', '["Push Notifications", "Background App Refresh", "Location Services", "iCloud Sync"]', 'Battery', '["Standard", "Plus", "Pro", "Max"]', (SELECT id FROM profiles WHERE email = 'system@portnox.com' LIMIT 1)),

-- IoT Devices
('IP Security Camera', 'iot', '["802.1X-EAP-TLS", "MAC-based", "Pre-shared Key"]', '["Physical Security", "Surveillance", "Monitoring", "Access Control"]', '["VLAN Isolation", "Firmware Updates", "Certificate Lifecycle", "Network Segmentation"]', '["Default Credentials", "Firmware Vulnerabilities", "Network Exposure", "Privacy Concerns"]', '["Axis", "Hikvision", "Dahua", "Bosch", "Hanwha"]', 'high', 'security_critical', 'Often lack advanced authentication, require careful network segmentation', '["RTSP Streaming", "HTTP Management", "ONVIF Protocol", "Motion Detection"]', 'PoE/AC Power', '["Fixed", "PTZ", "Dome", "Bullet"]', (SELECT id FROM profiles WHERE email = 'system@portnox.com' LIMIT 1)),

('VoIP Desk Phone', 'network_infrastructure', '["802.1X-EAP-TLS", "HTTP Digest", "LLDP-MED", "VLAN Assignment"]', '["Desktop Phones", "Conference Rooms", "Reception", "Emergency Phones"]', '["VLAN Tagging", "PoE Requirements", "QoS Configuration", "Emergency Services"]', '["Voice Privacy", "System Availability", "Emergency Access", "Toll Fraud"]', '["Cisco IP Phones", "Poly", "Yealink", "Avaya", "Mitel"]', 'medium', 'business_standard', 'Well-standardized with good 802.1X support and automatic VLAN assignment', '["SIP Protocol", "RTP Media", "LLDP Discovery", "HTTP Provisioning"]', 'PoE', '["Desktop", "Wireless", "Conference", "Video Phone"]', (SELECT id FROM profiles WHERE email = 'system@portnox.com' LIMIT 1));

-- Add use cases to use_case_library
INSERT INTO use_case_library (title, description, category, priority, complexity, industry_focus, authentication_methods, network_requirements, security_considerations, implementation_steps, success_criteria, common_challenges, best_practices, related_technologies, compliance_requirements, created_by) VALUES

('Enterprise 802.1X Deployment', 'Comprehensive enterprise network access control with certificate-based authentication', 'Employee Access', 'high', 'medium', '["Enterprise", "Healthcare", "Financial Services", "Government"]', '["802.1X-EAP-TLS", "Machine Authentication", "User Authentication", "Certificate-based"]', '["Dynamic VLAN Assignment", "QoS Policies", "Network Segmentation", "Redundant Authentication"]', '["Certificate Lifecycle Management", "Posture Assessment", "Privilege Escalation Prevention", "Session Monitoring"]', '["Deploy PKI Infrastructure", "Configure RADIUS Server", "Implement 802.1X on Switches", "Deploy Certificates", "Configure Dynamic VLAN Assignment", "Implement Posture Assessment", "Configure Monitoring"]', '["99.9% Authentication Success Rate", "< 10 second authentication time", "Zero unauthorized access incidents", "Automated certificate renewal"]', '["Certificate Deployment Complexity", "Legacy Device Support", "User Training", "Performance Impact", "Troubleshooting Complexity"]', '["Gradual Rollout", "Comprehensive Testing", "User Training Program", "Monitoring and Alerting", "Change Management Process"]', '["PKI", "RADIUS", "LDAP/AD", "SIEM", "NAC", "Endpoint Protection"]', '["SOX", "HIPAA", "PCI-DSS", "ISO 27001", "NIST Cybersecurity Framework"]', (SELECT id FROM profiles WHERE email = 'system@portnox.com' LIMIT 1)),

('Zero Trust BYOD Access', 'Secure access for personal devices with comprehensive policy enforcement', 'BYOD', 'high', 'high', '["Enterprise", "Education", "Healthcare", "Technology"]', '["802.1X-PEAP", "802.1X-EAP-TTLS", "Certificate-based", "MDM Integration"]', '["Guest Network Isolation", "Device Registration", "Bandwidth Limiting", "Content Filtering"]', '["Device Compliance", "Data Segregation", "Remote Wipe Capability", "Privacy Protection"]', '["Establish BYOD Policy", "Deploy MDM Solution", "Configure Guest Networks", "Implement Device Registration", "Deploy Compliance Policies", "Configure Data Protection", "User Training"]', '["95% Device Registration Rate", "Zero Corporate Data Breaches", "User Satisfaction > 85%", "Compliance with Privacy Regulations"]', '["Device Diversity", "User Resistance", "Privacy Concerns", "Support Complexity", "Policy Enforcement"]', '["Clear BYOD Policy", "User Education", "Minimal Friction Registration", "Privacy-First Approach", "Tiered Access Model"]', '["MDM", "MAM", "Cloud Services", "VPN", "DLP", "Mobile Security"]', '["GDPR", "CCPA", "HIPAA", "Corporate Data Protection Policies"]', (SELECT id FROM profiles WHERE email = 'system@portnox.com' LIMIT 1)),

('IoT Device Security Framework', 'Comprehensive IoT device onboarding and lifecycle management', 'IoT Security', 'high', 'very_high', '["Manufacturing", "Healthcare", "Smart Buildings", "Retail", "Education"]', '["802.1X-EAP-TLS", "MAC-based Authentication", "Certificate Provisioning", "Device Fingerprinting"]', '["IoT VLAN Segmentation", "Micro-segmentation", "East-West Traffic Control", "OT Network Integration"]', '["Device Identity Verification", "Firmware Integrity", "Communication Encryption", "Anomaly Detection"]', '["IoT Device Discovery", "Device Categorization", "Certificate Deployment", "Network Segmentation", "Policy Enforcement", "Monitoring Implementation", "Incident Response"]', '["100% Device Visibility", "Automated Policy Application", "Zero IoT-related Breaches", "Operational Continuity"]', '["Device Diversity", "Legacy Device Support", "Scalability", "Operational Impact", "Vendor Coordination"]', '["Device Inventory Management", "Risk-based Segmentation", "Automated Policies", "Continuous Monitoring", "Vendor Engagement"]', '["IoT Security Platform", "Network Segmentation", "SIEM", "Asset Management", "Certificate Management"]', '["IEC 62443", "NIST IoT Framework", "Industry-specific IoT Standards"]', (SELECT id FROM profiles WHERE email = 'system@portnox.com' LIMIT 1));

-- Add comprehensive requirements to requirements_library
INSERT INTO requirements_library (title, description, category, priority, implementation_approach, verification_methods, dependencies, related_standards, typical_timeline, cost_impact, risk_level, industry_specific, compliance_frameworks, created_by) VALUES

('Enterprise PKI Infrastructure', 'Deploy and manage Public Key Infrastructure for certificate-based authentication', 'Authentication Infrastructure', 'high', 'Deploy enterprise CA hierarchy with automated certificate enrollment and lifecycle management', '["Certificate Validation Testing", "CA Security Audit", "Certificate Renewal Testing", "Revocation Testing"]', '["Active Directory", "DNS Infrastructure", "Network Connectivity", "Security Policies"]', '["RFC 5280", "PKCS Standards", "X.509 Certificate Profile"]', '3-6 months', 'high', 'medium', '["Healthcare", "Financial Services", "Government"]', '["FIPS 140-2", "Common Criteria", "FISMA"]', (SELECT id FROM profiles WHERE email = 'system@portnox.com' LIMIT 1)),

('Network Micro-Segmentation', 'Implement logical network segmentation using VLANs and access control lists', 'Network Architecture', 'high', 'Design and implement VLAN strategy with dynamic assignment and micro-segmentation', '["Network Scanning", "Traffic Analysis", "Access Testing", "Performance Monitoring"]', '["Network Infrastructure", "VLAN Capable Switches", "Routing Equipment", "Firewall Rules"]', '["IEEE 802.1Q", "IEEE 802.1X", "NIST Network Segmentation Guidance"]', '2-4 months', 'medium', 'low', '["Healthcare", "Financial Services", "Manufacturing"]', '["PCI-DSS", "HIPAA", "SOX", "IEC 62443"]', (SELECT id FROM profiles WHERE email = 'system@portnox.com' LIMIT 1)),

('Zero Trust Network Access', 'Implement comprehensive Zero Trust architecture with application-level security', 'Zero Trust', 'very_high', 'Deploy ZTNA solution with device compliance and application-level security controls', '["Device Compliance Testing", "Application Access Testing", "Security Policy Validation", "Performance Testing"]', '["Identity Provider", "Device Management", "Application Gateways", "Network Infrastructure"]', '["NIST Zero Trust Architecture", "Zero Trust Maturity Model", "CISA Zero Trust Guidance"]', '4-8 months', 'high', 'medium', '["Enterprise", "Financial Services", "Government", "Healthcare"]', '["SOC 2", "ISO 27001", "NIST Cybersecurity Framework", "FedRAMP"]', (SELECT id FROM profiles WHERE email = 'system@portnox.com' LIMIT 1));

-- Add resource tags for categorization
INSERT INTO resource_tags (name, color_code, description, created_by) VALUES
('High-Security', '#dc2626', 'Resources requiring enhanced security measures', (SELECT id FROM profiles WHERE email = 'system@portnox.com' LIMIT 1)),
('Cloud-First', '#3b82f6', 'Cloud-native solutions and integrations', (SELECT id FROM profiles WHERE email = 'system@portnox.com' LIMIT 1)),
('Zero-Trust', '#10b981', 'Zero Trust architecture components', (SELECT id FROM profiles WHERE email = 'system@portnox.com' LIMIT 1)),
('Enterprise-Scale', '#ef4444', 'Enterprise-scale and high-availability solutions', (SELECT id FROM profiles WHERE email = 'system@portnox.com' LIMIT 1)),
('IoT-Ready', '#06b6d4', 'IoT and OT device management capabilities', (SELECT id FROM profiles WHERE email = 'system@portnox.com' LIMIT 1)),
('AI-Enhanced', '#a855f7', 'AI and machine learning enhanced capabilities', (SELECT id FROM profiles WHERE email = 'system@portnox.com' LIMIT 1)),
('Compliance', '#8b5cf6', 'Compliance and regulatory requirement solutions', (SELECT id FROM profiles WHERE email = 'system@portnox.com' LIMIT 1)),
('Cost-Effective', '#22c55e', 'Budget-friendly solutions for SMB', (SELECT id FROM profiles WHERE email = 'system@portnox.com' LIMIT 1)),
('Real-Time', '#f97316', 'Real-time processing and monitoring capabilities', (SELECT id FROM profiles WHERE email = 'system@portnox.com' LIMIT 1)),
('Legacy-Support', '#f59e0b', 'Solutions supporting legacy systems and protocols', (SELECT id FROM profiles WHERE email = 'system@portnox.com' LIMIT 1));

-- Add comprehensive resource categories
INSERT INTO resource_categories (name, resource_type, description, color_code, created_by) VALUES
('Enterprise Networking', 'vendor', 'Enterprise-grade networking equipment and solutions', '#1f2937', (SELECT id FROM profiles WHERE email = 'system@portnox.com' LIMIT 1)),
('Cloud Security', 'vendor', 'Cloud-based security and identity solutions', '#3b82f6', (SELECT id FROM profiles WHERE email = 'system@portnox.com' LIMIT 1)),
('Identity Management', 'vendor', 'Identity and access management platforms', '#8b5cf6', (SELECT id FROM profiles WHERE email = 'system@portnox.com' LIMIT 1)),
('Mobile Security', 'vendor', 'Mobile device management and security solutions', '#06b6d4', (SELECT id FROM profiles WHERE email = 'system@portnox.com' LIMIT 1)),
('SaaS Applications', 'vendor', 'Software as a Service applications and platforms', '#10b981', (SELECT id FROM profiles WHERE email = 'system@portnox.com' LIMIT 1)),
('Productivity Tools', 'use_case', 'Business productivity and collaboration use cases', '#22c55e', (SELECT id FROM profiles WHERE email = 'system@portnox.com' LIMIT 1)),
('Security Operations', 'use_case', 'Security monitoring and operations use cases', '#dc2626', (SELECT id FROM profiles WHERE email = 'system@portnox.com' LIMIT 1)),
('Network Infrastructure', 'requirement', 'Core network infrastructure requirements', '#1f2937', (SELECT id FROM profiles WHERE email = 'system@portnox.com' LIMIT 1)),
('Authentication Systems', 'requirement', 'Authentication and identity requirements', '#8b5cf6', (SELECT id FROM profiles WHERE email = 'system@portnox.com' LIMIT 1)),
('Compliance Standards', 'requirement', 'Regulatory compliance requirements', '#7c3aed', (SELECT id FROM profiles WHERE email = 'system@portnox.com' LIMIT 1));