-- Add comprehensive vendor library for networking, security, and compliance
INSERT INTO vendor_library (vendor_name, category, vendor_type, support_level, portnox_integration_level, documentation_links, status, supported_protocols, integration_methods, created_by) VALUES
-- Networking Wired Vendors
('Aruba Networks', 'wired_networking', 'switch', 'full', 'native', '["https://www.arubanetworks.com/support/"]', 'active', '["802.1X", "MAB", "Dynamic VLAN", "User Role Assignment"]', '["ClearPass Integration", "Policy Enforcement", "Dynamic Segmentation"]', '00000000-0000-0000-0000-000000000000'),
('Extreme Networks', 'wired_networking', 'switch', 'full', 'native', '["https://extremenetworks.com/support/"]', 'active', '["802.1X", "MAB", "LLDP-MED", "Fabric Attach"]', '["NAC Integration", "Fabric Connect"]', '00000000-0000-0000-0000-000000000000'),
('Juniper Networks', 'wired_networking', 'switch', 'full', 'native', '["https://www.juniper.net/support/"]', 'active', '["802.1X", "MAB", "EX Series Integration", "Junos Pulse"]', '["Pulse Secure", "Mist AI"]', '00000000-0000-0000-0000-000000000000'),
('Huawei', 'wired_networking', 'switch', 'partial', 'api', '["https://support.huawei.com/"]', 'active', '["802.1X", "MAB", "HWTACACS"]', '["CloudEngine", "Agile Controller"]', '00000000-0000-0000-0000-000000000000'),
('Dell Technologies', 'wired_networking', 'switch', 'full', 'native', '["https://www.dell.com/support/"]', 'active', '["802.1X", "MAB", "LLDP", "OS10 Management"]', '["OS10 Integration", "PowerSwitch"]', '00000000-0000-0000-0000-000000000000'),

-- Networking Wireless Vendors
('Aruba Wireless', 'wireless_networking', 'access_point', 'full', 'native', '["https://www.arubanetworks.com/support/"]', 'active', '["WiFi 6E", "802.1X", "WPA3", "Dynamic VLAN"]', '["Instant On", "Central Cloud", "ClearPass Integration"]', '00000000-0000-0000-0000-000000000000'),
('Ruckus Networks', 'wireless_networking', 'access_point', 'full', 'native', '["https://support.ruckuswireless.com/"]', 'active', '["WiFi 6", "802.1X", "DPSK", "BeamFlex"]', '["SmartZone", "Unleashed"]', '00000000-0000-0000-0000-000000000000'),
('Meraki', 'wireless_networking', 'access_point', 'full', 'api', '["https://documentation.meraki.com/"]', 'active', '["WiFi 6", "802.1X", "Splash Pages", "Group Policies"]', '["Cloud Managed", "Dashboard API"]', '00000000-0000-0000-0000-000000000000'),
('Ubiquiti', 'wireless_networking', 'access_point', 'partial', 'api', '["https://help.ui.com/"]', 'active', '["WiFi 6", "VLAN", "Guest Portal", "UniFi Network"]', '["UniFi Controller", "Dream Machine"]', '00000000-0000-0000-0000-000000000000'),
('Mist (Juniper)', 'wireless_networking', 'access_point', 'full', 'native', '["https://www.mist.com/support/"]', 'active', '["WiFi 6E", "AI Insights", "Location Services", "Marvis AI"]', '["AI Driven", "Cloud Native"]', '00000000-0000-0000-0000-000000000000'),

-- Firewall Vendors
('Palo Alto Networks', 'firewall', 'ngfw', 'full', 'api', '["https://docs.paloaltonetworks.com/"]', 'active', '["Next-Gen Firewall", "User-ID", "GlobalProtect", "Threat Prevention"]', '["GlobalProtect", "Prisma Access", "User-ID"]', '00000000-0000-0000-0000-000000000000'),
('Fortinet', 'firewall', 'ngfw', 'full', 'api', '["https://docs.fortinet.com/"]', 'active', '["NGFW", "SD-WAN", "ZTNA", "Security Fabric"]', '["FortiGate", "FortiOS", "Security Fabric"]', '00000000-0000-0000-0000-000000000000'),
('Check Point', 'firewall', 'ngfw', 'full', 'api', '["https://supportcenter.checkpoint.com/"]', 'active', '["Infinity Architecture", "SmartConsole", "Harmony", "CloudGuard"]', '["SmartConsole", "Harmony"]', '00000000-0000-0000-0000-000000000000'),
('SonicWall', 'firewall', 'ngfw', 'partial', 'api', '["https://www.sonicwall.com/support/"]', 'active', '["NGFW", "Capture Security", "SSL VPN", "WAN Acceleration"]', '["SonicWall NSA", "Capture Security"]', '00000000-0000-0000-0000-000000000000'),
('pfSense', 'firewall', 'open_source', 'partial', 'manual', '["https://docs.netgate.com/"]', 'active', '["Open Source", "pfBlocker", "Snort", "Community Packages"]', '["Open Source", "Community"]', '00000000-0000-0000-0000-000000000000'),

-- IDP (Identity Provider) Vendors  
('Active Directory', 'idp', 'on_premises', 'full', 'native', '["https://docs.microsoft.com/en-us/windows-server/identity/"]', 'active', '["LDAP", "Kerberos", "NTLM", "ADFS"]', '["Domain Services", "Certificate Services", "Federation"]', '00000000-0000-0000-0000-000000000000'),
('Azure Active Directory', 'idp', 'cloud', 'full', 'api', '["https://docs.microsoft.com/en-us/azure/active-directory/"]', 'active', '["SAML", "OAuth", "OpenID Connect", "Conditional Access"]', '["Conditional Access", "MFA", "Hybrid Identity"]', '00000000-0000-0000-0000-000000000000'),
('Okta', 'idp', 'cloud', 'full', 'api', '["https://developer.okta.com/"]', 'active', '["SAML", "OAuth", "SCIM", "Adaptive MFA"]', '["Universal Directory", "Adaptive MFA"]', '00000000-0000-0000-0000-000000000000'),
('Ping Identity', 'idp', 'hybrid', 'full', 'api', '["https://docs.pingidentity.com/"]', 'active', '["SAML", "OAuth", "OpenID Connect", "Risk-based Auth"]', '["PingFederate", "PingDirectory"]', '00000000-0000-0000-0000-000000000000'),
('OneLogin', 'idp', 'cloud', 'full', 'api', '["https://developers.onelogin.com/"]', 'active', '["SAML", "OAuth", "RADIUS", "SmartFactor MFA"]', '["SmartFactor", "Desktop SSO"]', '00000000-0000-0000-0000-000000000000'),

-- MDM Vendors
('Microsoft Intune', 'mdm', 'cloud', 'full', 'api', '["https://docs.microsoft.com/en-us/mem/intune/"]', 'active', '["Device Compliance", "App Protection", "Conditional Access", "Autopilot"]', '["Autopilot", "Compliance Policies", "Conditional Access"]', '00000000-0000-0000-0000-000000000000'),
('VMware Workspace ONE', 'mdm', 'cloud', 'full', 'api', '["https://docs.vmware.com/en/VMware-Workspace-ONE/"]', 'active', '["UEM", "App Management", "Content Collaboration", "Analytics"]', '["UEM", "Workspace Intelligence"]', '00000000-0000-0000-0000-000000000000'),
('Jamf', 'mdm', 'cloud', 'full', 'api', '["https://developer.jamf.com/"]', 'active', '["Apple Management", "Zero-Touch Deployment", "Threat Defense"]', '["Jamf Pro", "Jamf Protect", "Apple Focus"]', '00000000-0000-0000-0000-000000000000'),
('MobileIron', 'mdm', 'hybrid', 'partial', 'api', '["https://docs.mobileiron.com/"]', 'active', '["Device Management", "App Wrapping", "Secure Connectivity"]', '["Core Connector", "Tunnel"]', '00000000-0000-0000-0000-000000000000'),
('Citrix Endpoint Management', 'mdm', 'cloud', 'full', 'api', '["https://docs.citrix.com/"]', 'active', '["Device Management", "App Management", "Secure Productivity"]', '["Secure Mail", "Secure Web"]', '00000000-0000-0000-0000-000000000000'),

-- EDR Vendors
('CrowdStrike Falcon', 'edr', 'cloud', 'full', 'api', '["https://falcon.crowdstrike.com/support/"]', 'active', '["Endpoint Detection", "Threat Hunting", "Incident Response", "Cloud Workload Protection"]', '["Threat Graph", "Real-time Response", "Threat Hunting"]', '00000000-0000-0000-0000-000000000000'),
('SentinelOne', 'edr', 'cloud', 'full', 'api', '["https://support.sentinelone.com/"]', 'active', '["AI-Powered Detection", "Autonomous Response", "Threat Hunting", "Rollback"]', '["Singularity Platform", "Autonomous Response"]', '00000000-0000-0000-0000-000000000000'),
('Microsoft Defender for Endpoint', 'edr', 'cloud', 'full', 'api', '["https://docs.microsoft.com/en-us/microsoft-365/security/"]', 'active', '["Behavioral Analysis", "Cloud Detection", "Automated Investigation", "Threat Analytics"]', '["Threat & Vulnerability", "Attack Surface Reduction"]', '00000000-0000-0000-0000-000000000000'),
('Carbon Black (VMware)', 'edr', 'cloud', 'full', 'api', '["https://docs.vmware.com/en/VMware-Carbon-Black/"]', 'active', '["Endpoint Standard", "Endpoint Advanced", "Audit and Remediation"]', '["CB Cloud", "CB Defense"]', '00000000-0000-0000-0000-000000000000'),
('Cylance (BlackBerry)', 'edr', 'hybrid', 'partial', 'api', '["https://docs.blackberry.com/en/endpoint-management/"]', 'active', '["AI Prevention", "EDR", "Memory Protection", "Script Control"]', '["AI Prevention", "Optics"]', '00000000-0000-0000-0000-000000000000'),

-- SIEM Vendors
('Splunk', 'siem', 'hybrid', 'full', 'api', '["https://docs.splunk.com/"]', 'active', '["Log Management", "Security Analytics", "SOAR", "UEBA"]', '["Enterprise Security", "Phantom", "UEBA"]', '00000000-0000-0000-0000-000000000000'),
('IBM QRadar', 'siem', 'hybrid', 'full', 'api', '["https://www.ibm.com/support/knowledgecenter/SS42VS"]', 'active', '["Security Intelligence", "Network Insights", "Risk Management", "Incident Forensics"]', '["Risk Manager", "Incident Forensics"]', '00000000-0000-0000-0000-000000000000'),
('Microsoft Sentinel', 'siem', 'cloud', 'full', 'api', '["https://docs.microsoft.com/en-us/azure/sentinel/"]', 'active', '["Cloud-Native SIEM", "AI/ML Analytics", "SOAR", "Threat Intelligence"]', '["Cloud Native", "AI/ML", "SOAR"]', '00000000-0000-0000-0000-000000000000'),
('LogRhythm', 'siem', 'hybrid', 'full', 'api', '["https://docs.logrhythm.com/"]', 'active', '["NextGen SIEM", "UEBA", "SOAR", "Threat Lifecycle Management"]', '["NextGen SIEM", "ResolvR"]', '00000000-0000-0000-0000-000000000000'),
('ArcSight (Micro Focus)', 'siem', 'on_premises', 'partial', 'api', '["https://www.microfocus.com/documentation/arcsight/"]', 'active', '["Enterprise Security Manager", "Threat Intelligence", "Risk Analytics"]', '["ESM", "Intelligence"]', '00000000-0000-0000-0000-000000000000');

-- Add comprehensive use cases
INSERT INTO use_case_library (title, category, priority, description, business_value, technical_requirements, implementation_complexity, estimated_timeline, success_metrics, created_by) VALUES
-- Security Use Cases
('Zero Trust Network Access', 'security', 'high', 'Implement zero trust architecture with continuous verification of all users and devices', 'Reduces security breaches by 70%, improves compliance posture', '["NAC Solution", "MFA", "Device Compliance", "Risk Assessment"]', 'high', '3-6 months', '["Reduced security incidents", "100% device visibility", "Policy compliance rate >95%"]', '00000000-0000-0000-0000-000000000000'),
('BYOD Security Framework', 'security', 'high', 'Secure bring-your-own-device program with automated onboarding and compliance', 'Increases employee satisfaction while maintaining security', '["MDM Integration", "Certificate Management", "Guest Network", "Policy Engine"]', 'medium', '2-4 months', '["Device enrollment rate >90%", "Security incident reduction", "User satisfaction score >4.5"]', '00000000-0000-0000-0000-000000000000'),
('IoT Device Management', 'security', 'medium', 'Automated discovery, classification, and security policy enforcement for IoT devices', 'Reduces IoT-related security risks and improves operational visibility', '["Device Fingerprinting", "Network Segmentation", "Behavior Analytics", "Policy Automation"]', 'high', '4-8 months', '["100% IoT device visibility", "Automated policy enforcement", "Reduced manual overhead"]', '00000000-0000-0000-0000-000000000000'),
('Compliance Automation', 'compliance', 'high', 'Automated compliance reporting and audit trail for regulatory requirements', 'Reduces audit preparation time by 80%, ensures continuous compliance', '["Audit Logging", "Report Generation", "Policy Templates", "Risk Assessment"]', 'medium', '2-3 months', '["Audit readiness time <1 week", "Compliance score >95%", "Automated reporting"]', '00000000-0000-0000-0000-000000000000'),

-- Operational Use Cases
('Automated Guest Access', 'operations', 'medium', 'Self-service guest registration with automatic provisioning and time-limited access', 'Improves visitor experience while maintaining security controls', '["Self-Service Portal", "SMS/Email Integration", "Time-Based Policies", "Sponsor Approval"]', 'low', '1-2 months', '["Guest satisfaction >4.0", "IT request reduction >50%", "Security policy compliance"]', '00000000-0000-0000-0000-000000000000'),
('Network Troubleshooting', 'operations', 'medium', 'Automated network issue detection and resolution with detailed forensics', 'Reduces MTTR by 60%, improves network availability', '["Real-time Monitoring", "Event Correlation", "Automated Remediation", "Forensic Analysis"]', 'medium', '2-3 months', '["MTTR reduction >60%", "Network uptime >99.5%", "Automated issue resolution >40%"]', '00000000-0000-0000-0000-000000000000'),
('Bandwidth Optimization', 'operations', 'low', 'Dynamic bandwidth allocation based on user roles and application priorities', 'Improves application performance and user experience', '["QoS Integration", "Application Recognition", "Dynamic Policies", "Usage Analytics"]', 'medium', '2-4 months', '["Application response time improvement", "Bandwidth utilization optimization", "User satisfaction increase"]', '00000000-0000-0000-0000-000000000000'),

-- Industry-Specific Use Cases  
('Healthcare HIPAA Compliance', 'healthcare', 'high', 'HIPAA-compliant network access with PHI protection and audit trails', 'Ensures regulatory compliance and protects patient data', '["Encryption", "Audit Logging", "Role-Based Access", "Risk Assessment"]', 'high', '3-6 months', '["HIPAA compliance certification", "Zero PHI breaches", "Audit trail completeness"]', '00000000-0000-0000-0000-000000000000'),
('Financial PCI DSS Compliance', 'finance', 'high', 'PCI DSS compliant network segmentation and cardholder data protection', 'Maintains payment card industry compliance and customer trust', '["Network Segmentation", "Encryption", "Access Controls", "Monitoring"]', 'high', '4-8 months', '["PCI DSS certification", "Cardholder data protection", "Compliance audit pass"]', '00000000-0000-0000-0000-000000000000'),
('Educational Campus Security', 'education', 'medium', 'Multi-tenant network access for students, faculty, and guests with appropriate controls', 'Balances open access with security requirements', '["Multi-Tenancy", "Guest Access", "Content Filtering", "Usage Monitoring"]', 'medium', '2-4 months', '["User satisfaction >4.0", "Security incident reduction", "Policy compliance >90%"]', '00000000-0000-0000-0000-000000000000'),
('Manufacturing OT Security', 'manufacturing', 'high', 'Operational technology network security with minimal disruption to production', 'Protects critical infrastructure while maintaining operational continuity', '["OT/IT Segmentation", "Asset Discovery", "Anomaly Detection", "Production Continuity"]', 'high', '6-12 months', '["Zero production disruptions", "OT asset visibility", "Cyber threat reduction"]', '00000000-0000-0000-0000-000000000000');

-- Add comprehensive requirements
INSERT INTO requirements_library (title, category, description, acceptance_criteria, business_justification, technical_specifications, dependencies, risk_level, implementation_effort, created_by) VALUES
-- Functional Requirements
('Multi-Factor Authentication', 'authentication', 'All network access must require multi-factor authentication for enhanced security', 'MFA required for all users, support for multiple MFA methods, integration with existing identity providers', 'Reduces password-related breaches by 99.9%, meets compliance requirements', '{"supported_methods": ["TOTP", "SMS", "Push", "Biometric"], "integration": ["AD", "Azure AD", "Okta"], "fallback": "Emergency codes"}', '["Identity Provider", "Mobile Device Management"]', 'low', 'medium', '00000000-0000-0000-0000-000000000000'),
('Device Compliance Checking', 'security', 'Automated verification of device compliance before network access', 'Real-time compliance checking, automated remediation, reporting capabilities', 'Prevents non-compliant devices from accessing sensitive resources', '{"checks": ["Antivirus", "OS Updates", "Encryption", "Certificate"], "enforcement": "Block non-compliant", "remediation": "Automated"}', '["MDM Solution", "Certificate Authority"]', 'medium', 'high', '00000000-0000-0000-0000-000000000000'),
('Network Segmentation', 'network', 'Dynamic network segmentation based on user roles and device types', 'Automated VLAN assignment, microsegmentation capabilities, policy enforcement', 'Limits blast radius of security incidents, improves network performance', '{"segmentation": "Dynamic", "granularity": "User/Device based", "enforcement": "Real-time", "scalability": "Enterprise"}', '["VLAN Infrastructure", "Policy Engine"]', 'high', 'high', '00000000-0000-0000-0000-000000000000'),
('Guest Access Management', 'operations', 'Self-service guest access with automated provisioning and monitoring', 'Self-service portal, sponsor approval workflow, time-limited access, usage monitoring', 'Improves visitor experience while maintaining security controls', '{"portal": "Self-service", "approval": "Sponsor-based", "duration": "Time-limited", "monitoring": "Real-time"}', '["Web Portal", "Email/SMS Gateway"]', 'low', 'low', '00000000-0000-0000-0000-000000000000'),

-- Non-Functional Requirements
('High Availability', 'infrastructure', '99.9% uptime with redundancy and failover capabilities', 'Less than 8.76 hours downtime per year, automatic failover, no single points of failure', 'Ensures business continuity and user productivity', '{"uptime": "99.9%", "failover": "Automatic", "redundancy": "N+1", "monitoring": "24/7"}', '["Redundant Infrastructure", "Load Balancing"]', 'high', 'high', '00000000-0000-0000-0000-000000000000'),
('Scalability', 'performance', 'Support for 10,000+ concurrent users with linear performance scaling', 'Performance testing validated, horizontal scaling capability, resource optimization', 'Accommodates business growth without performance degradation', '{"capacity": "10,000+ users", "scaling": "Horizontal", "performance": "Linear", "optimization": "Automatic"}', '["Scalable Architecture", "Performance Monitoring"]', 'medium', 'high', '00000000-0000-0000-0000-000000000000'),
('Audit and Compliance', 'compliance', 'Comprehensive logging and reporting for regulatory compliance', 'Complete audit trail, automated reporting, data retention policies, compliance dashboards', 'Meets regulatory requirements and reduces audit preparation time', '{"logging": "Comprehensive", "retention": "7 years", "reports": "Automated", "compliance": "SOX/HIPAA/PCI"}', '["Log Management", "Report Engine"]', 'medium', 'medium', '00000000-0000-0000-0000-000000000000'),

-- Integration Requirements
('SIEM Integration', 'integration', 'Real-time security event forwarding to SIEM platforms', 'Real-time event streaming, standardized log format, threat intelligence correlation', 'Enhances security operations center capabilities and incident response', '{"streaming": "Real-time", "format": "CEF/LEEF/JSON", "protocols": ["Syslog", "HTTPS", "Kafka"], "enrichment": "Context-aware"}', '["SIEM Platform", "Network Connectivity"]', 'low', 'medium', '00000000-0000-0000-0000-000000000000'),
('Identity Provider Sync', 'integration', 'Automated synchronization with enterprise identity providers', 'Real-time user/group sync, attribute mapping, error handling and recovery', 'Ensures consistent access policies and reduces administrative overhead', '{"sync": "Real-time", "protocols": ["LDAP", "SCIM", "Graph API"], "mapping": "Flexible", "recovery": "Automatic"}', '["Identity Provider", "Directory Services"]', 'medium', 'medium', '00000000-0000-0000-0000-000000000000'),
('Cloud Integration', 'integration', 'Hybrid cloud support with cloud-native integrations', 'Multi-cloud support, API-first architecture, cloud-native scaling', 'Enables modern cloud architectures and hybrid deployments', '{"clouds": ["AWS", "Azure", "GCP"], "architecture": "API-first", "scaling": "Cloud-native", "management": "Unified"}', '["Cloud Platform", "API Gateway"]', 'medium', 'high', '00000000-0000-0000-0000-000000000000');