-- Add comprehensive vendor library with correct column names
-- Insert comprehensive vendor data using the actual table structure

INSERT INTO vendor_library (vendor_name, vendor_type, category, description, website_url, support_contact, models, supported_protocols, integration_methods, portnox_compatibility, configuration_templates, known_limitations, firmware_requirements, documentation_links, support_level, portnox_integration_level, portnox_documentation, certifications, status, created_by) VALUES

-- Wired Infrastructure Vendors
('HPE Aruba Switching', 'network_infrastructure', 'wired', 'Enterprise switching solutions with ClearPass integration', 'https://www.arubanetworks.com', '{"email": "support@arubanetworks.com", "phone": "+1-408-227-4500"}', '["6200F", "6300F", "6300M", "6400", "8325", "8360", "8400"]', '["802.1X", "MAB", "LLDP", "SNMP", "RADIUS"]', '["RADIUS", "ClearPass", "Central"]', '{"level": "excellent", "certified": true, "testing_status": "validated"}', '["campus_switch", "l3_routing", "security_basic"]', '["firmware_compatibility"]', '["ArubaOS-CX 10.08+"]', '{"datasheet": "arubanetworks.com/products/switches/", "config_guide": "arubanetworks.com/support/"}', 'enterprise', 'certified', '{"integration_guide": "portnox.com/integrations/aruba", "config_examples": "yes"}', '["Portnox Certified", "ISO 9001"]', 'active', NULL),

('Cisco Catalyst', 'network_infrastructure', 'wired', 'Industry-leading enterprise switching portfolio', 'https://www.cisco.com', '{"email": "support@cisco.com", "phone": "+1-800-553-2447"}', '["9200", "9300", "9400", "9500", "9600", "3850", "2960X"]', '["802.1X", "MAB", "NEAT", "RADIUS", "TACACS+"]', '["RADIUS", "ISE", "DNAC"]', '{"level": "excellent", "certified": true, "testing_status": "validated"}', '["basic_l2", "l3_routing", "security", "datacenter"]', '["licensing_complexity"]', '["IOS-XE 16.12+", "IOS 15.2+"]', '{"datasheet": "cisco.com/c/en/us/products/switches/", "config_guide": "cisco.com/c/en/us/support/"}', 'enterprise', 'certified', '{"integration_guide": "portnox.com/integrations/cisco", "config_examples": "yes"}', '["Portnox Certified", "Common Criteria"]', 'active', NULL),

('Juniper EX Series', 'network_infrastructure', 'wired', 'High-performance Ethernet switches', 'https://www.juniper.net', '{"email": "support@juniper.net", "phone": "+1-888-314-5822"}', '["EX2300", "EX3400", "EX4300", "EX4400", "EX4600", "EX4650"]', '["802.1X", "RADIUS", "TACACS+", "SNMP"]', '["RADIUS", "Junos Space"]', '{"level": "good", "certified": false, "testing_status": "compatible"}', '["basic_l2", "l3_routing", "security"]', '["junos_syntax"]', '["Junos 18.4+"]', '{"datasheet": "juniper.net/us/en/products/switches/", "config_guide": "juniper.net/documentation/"}', 'enterprise', 'compatible', '{"integration_guide": "portnox.com/integrations/juniper", "config_examples": "basic"}', '["FIPS 140-2"]', 'active', NULL),

-- Wireless Infrastructure Vendors  
('Cisco Wireless 9800', 'wireless_infrastructure', 'wireless', 'Enterprise wireless controllers and APs', 'https://www.cisco.com', '{"email": "support@cisco.com", "phone": "+1-800-553-2447"}', '["9800-CL", "9800-L", "9800-40", "9800-80", "9130AXI", "9136I"]', '["802.1X", "PSK", "RADIUS", "WPA3", "OWE"]', '["RADIUS", "ISE", "DNAC", "CAPWAP"]', '{"level": "excellent", "certified": true, "testing_status": "validated"}', '["enterprise", "guest", "byod", "iot"]', '["dna_licensing"]', '["IOS-XE 17.3+"]', '{"datasheet": "cisco.com/c/en/us/products/wireless/", "config_guide": "cisco.com/c/en/us/support/wireless/"}', 'enterprise', 'certified', '{"integration_guide": "portnox.com/integrations/cisco-wireless", "config_examples": "yes"}', '["Portnox Certified", "WiFi Alliance"]', 'active', NULL),

('HPE Aruba Central', 'wireless_infrastructure', 'wireless', 'Cloud-native network management', 'https://www.arubanetworks.com', '{"email": "support@arubanetworks.com", "phone": "+1-408-227-4500"}', '["515", "535", "555", "575", "635", "7030", "7205", "7220"]', '["802.1X", "PSK", "RADIUS", "WPA3", "Enhanced Open"]', '["RADIUS", "ClearPass", "Central Cloud"]', '{"level": "excellent", "certified": true, "testing_status": "validated"}', '["campus", "branch", "guest", "iot"]', '["cloud_dependency"]', '["ArubaOS 8.8+", "Instant 8.10+"]', '{"datasheet": "arubanetworks.com/products/wireless/", "config_guide": "arubanetworks.com/support/"}', 'enterprise', 'certified', '{"integration_guide": "portnox.com/integrations/aruba-wireless", "config_examples": "yes"}', '["Portnox Certified", "WiFi Alliance"]', 'active', NULL),

-- NAC/RADIUS Providers (Competitive Analysis)
('Cisco ISE', 'nac_radius', 'nac', 'Identity Services Engine', 'https://www.cisco.com/c/en/us/products/security/identity-services-engine/', '{"email": "support@cisco.com", "phone": "+1-800-553-2447"}', '["ISE 2.7", "ISE 3.0", "ISE 3.1", "ISE 3.2"]', '["RADIUS", "TACACS+", "EAP-TLS", "PEAP", "EAP-FAST"]', '["API", "pxGrid", "Active Directory"]', '{"level": "competitive", "certified": false, "testing_status": "alternative"}', '["policy_enforcement", "guest_access", "byod"]', '["complexity", "licensing_cost"]', '["ISE 3.0+"]', '{"datasheet": "cisco.com/c/en/us/products/security/identity-services-engine/", "config_guide": "cisco.com/c/en/us/support/security/"}', 'enterprise', 'competitive', '{"comparison_guide": "portnox.com/vs/cisco-ise", "migration_guide": "yes"}', '["Common Criteria"]', 'active', NULL),

('Aruba ClearPass', 'nac_radius', 'nac', 'Network access control platform', 'https://www.arubanetworks.com/products/security/network-access-control/', '{"email": "support@arubanetworks.com", "phone": "+1-408-227-4500"}', '["ClearPass 6.9", "ClearPass 6.10", "ClearPass 6.11"]', '["RADIUS", "TACACS+", "EAP-TLS", "PEAP", "EAP-TTLS"]', '["API", "Active Directory", "LDAP"]', '{"level": "competitive", "certified": false, "testing_status": "alternative"}', '["policy_manager", "guest", "onboard"]', '["aruba_dependency"]', '["ClearPass 6.9+"]', '{"datasheet": "arubanetworks.com/products/security/network-access-control/", "config_guide": "arubanetworks.com/support/"}', 'enterprise', 'competitive', '{"comparison_guide": "portnox.com/vs/clearpass", "migration_guide": "yes"}', '["Common Criteria"]', 'active', NULL),

-- Security Vendors (Integration Partners)
('Palo Alto Networks', 'security', 'firewall', 'Next-generation firewalls and security', 'https://www.paloaltonetworks.com', '{"email": "support@paloaltonetworks.com", "phone": "+1-866-898-9087"}', '["PA-220", "PA-850", "PA-3220", "PA-5220", "VM-Series"]', '["RADIUS", "SAML", "LDAP", "Kerberos"]', '["API", "User-ID", "GlobalProtect"]', '{"level": "good", "certified": false, "testing_status": "compatible"}', '["user_id_integration", "globalprotect"]', '["user_mapping"]', '["PAN-OS 10.0+"]', '{"datasheet": "paloaltonetworks.com/products/", "config_guide": "docs.paloaltonetworks.com/"}', 'enterprise', 'compatible', '{"integration_guide": "portnox.com/integrations/palo-alto", "config_examples": "basic"}', '["Common Criteria"]', 'active', NULL),

-- Identity Providers
('Microsoft Azure AD', 'identity_provider', 'identity', 'Cloud identity and access management', 'https://azure.microsoft.com/en-us/services/active-directory/', '{"email": "support@microsoft.com"}', '["Azure AD Free", "Azure AD P1", "Azure AD P2"]', '["SAML", "OAuth", "OpenID Connect", "RADIUS"]', '["Graph API", "SCIM", "LDAP"]', '{"level": "good", "certified": false, "testing_status": "compatible"}', '["sso", "conditional_access", "mfa"]', '["cloud_dependency"]', '["Current"]', '{"datasheet": "docs.microsoft.com/en-us/azure/active-directory/", "config_guide": "docs.microsoft.com/en-us/azure/"}', 'enterprise', 'compatible', '{"integration_guide": "portnox.com/integrations/azure-ad", "config_examples": "yes"}', '["SOC 2", "ISO 27001"]', 'active', NULL),

('Okta', 'identity_provider', 'identity', 'Identity and access management', 'https://www.okta.com', '{"email": "support@okta.com", "phone": "+1-888-722-7871"}', '["Workforce Identity", "Customer Identity", "Privileged Access"]', '["SAML", "OAuth", "OpenID Connect", "RADIUS"]', '["SCIM", "API", "LDAP"]', '{"level": "good", "certified": false, "testing_status": "compatible"}', '["sso", "mfa", "lifecycle"]', '["cost"]', '["Current"]', '{"datasheet": "okta.com/products/", "config_guide": "help.okta.com/"}', 'enterprise', 'compatible', '{"integration_guide": "portnox.com/integrations/okta", "config_examples": "yes"}', '["SOC 2", "FedRAMP"]', 'active', NULL),

-- MFA Providers
('Duo Security Cisco', 'mfa_provider', 'mfa', 'Multi-factor authentication', 'https://duo.com', '{"email": "support@duo.com", "phone": "+1-855-426-3872"}', '["Duo Free", "Duo MFA", "Duo Access", "Duo Beyond"]', '["RADIUS", "LDAP", "SAML", "REST API"]', '["API", "RADIUS Proxy", "AD Sync"]', '{"level": "excellent", "certified": true, "testing_status": "validated"}', '["radius_integration", "push_auth", "sso"]', '["none"]', '["Current"]', '{"datasheet": "duo.com/product/", "config_guide": "duo.com/docs/"}', 'enterprise', 'certified', '{"integration_guide": "portnox.com/integrations/duo", "config_examples": "yes"}', '["SOC 2", "FedRAMP"]', 'active', NULL),

-- Cloud Providers  
('Amazon Web Services', 'cloud_provider', 'cloud', 'Cloud computing platform', 'https://aws.amazon.com', '{"email": "support@aws.amazon.com"}', '["EC2", "VPC", "Directory Service", "SSO", "WorkSpaces"]', '["SAML", "OAuth", "RADIUS", "LDAP"]', '["API", "CloudFormation", "Directory Service"]', '{"level": "good", "certified": false, "testing_status": "compatible"}', '["cloud_deployment", "directory_service"]', '["complexity"]', '["Current"]', '{"datasheet": "aws.amazon.com/products/", "config_guide": "docs.aws.amazon.com/"}', 'enterprise', 'compatible', '{"integration_guide": "portnox.com/integrations/aws", "config_examples": "basic"}', '["SOC 1/2/3", "FedRAMP"]', 'active', NULL),

-- SIEM/EDR Vendors
('Splunk', 'siem_edr', 'siem', 'Security information and event management', 'https://www.splunk.com', '{"email": "support@splunk.com", "phone": "+1-866-438-7758"}', '["Enterprise", "Cloud", "Light", "Free"]', '["REST API", "Syslog", "SNMP"]', '["REST API", "Universal Forwarder", "HTTP Event Collector"]', '{"level": "excellent", "certified": true, "testing_status": "validated"}', '["siem_integration", "dashboards", "alerting"]', '["cost"]', '["8.0+"]', '{"datasheet": "splunk.com/en_us/products/", "config_guide": "docs.splunk.com/"}', 'enterprise', 'certified', '{"integration_guide": "portnox.com/integrations/splunk", "config_examples": "yes"}', '["SOC 2", "Common Criteria"]', 'active', NULL),

-- MDM Vendors
('Microsoft Intune', 'mdm_provider', 'mdm', 'Mobile device management', 'https://docs.microsoft.com/en-us/mem/intune/', '{"email": "support@microsoft.com"}', '["Intune", "Configuration Manager", "Autopilot"]', '["Azure AD", "Exchange", "SCEP", "RADIUS"]', '["Graph API", "PowerShell", "REST API"]', '{"level": "good", "certified": false, "testing_status": "compatible"}', '["device_compliance", "conditional_access"]', '["microsoft_dependency"]', '["Current"]', '{"datasheet": "docs.microsoft.com/en-us/mem/intune/", "config_guide": "docs.microsoft.com/en-us/mem/"}', 'enterprise', 'compatible', '{"integration_guide": "portnox.com/integrations/intune", "config_examples": "yes"}', '["SOC 2", "ISO 27001"]', 'active', NULL);