-- Enhanced vendor library with comprehensive data
INSERT INTO vendor_library (vendor_name, vendor_type, category, models, supported_protocols, integration_methods, portnox_compatibility, configuration_templates, known_limitations, firmware_requirements, documentation_links, support_level, status, created_by) VALUES

-- NAC Vendors
('Portnox', 'Network Access Control', 'NAC', 
 '["CORE", "CLEAR", "EDGE", "Cloud"]'::jsonb,
 '["RADIUS", "802.1X", "MAB", "TACACS+", "LDAP", "SAML"]'::jsonb,
 '["Native API", "REST API", "SAML SSO", "SCIM"]'::jsonb,
 '{"level": "native", "features": ["full_integration", "advanced_policies", "real_time_sync"]}'::jsonb,
 '{"available": true, "count": 25, "types": ["basic", "advanced", "industry_specific"]}'::jsonb,
 '[]'::jsonb,
 '{"minimum": "21.1", "recommended": "23.1", "latest": "23.5"}'::jsonb,
 '[{"title": "Admin Guide", "url": "https://docs.portnox.com", "type": "setup"}, {"title": "API Reference", "url": "https://api.portnox.com", "type": "api"}]'::jsonb,
 'full', 'active', auth.uid()),

-- Cisco Products
('Cisco ISE', 'Identity Services Engine', 'NAC',
 '["3355", "3365", "3375", "3395", "Virtual", "SNS-3415", "SNS-3495"]'::jsonb,
 '["RADIUS", "TACACS+", "802.1X", "MAB", "EAP-TLS", "PEAP", "EAP-TTLS"]'::jsonb,
 '["pxGrid", "REST API", "SDK", "ERS API"]'::jsonb,
 '{"level": "certified", "features": ["policy_sync", "threat_sharing", "context_sharing"]}'::jsonb,
 '{"available": true, "count": 15, "types": ["basic", "advanced"]}'::jsonb,
 '["Complex licensing", "High resource requirements"]'::jsonb,
 '{"minimum": "3.0", "recommended": "3.2", "latest": "3.3"}'::jsonb,
 '[{"title": "ISE Integration Guide", "url": "#", "type": "setup"}]'::jsonb,
 'full', 'active', auth.uid()),

('Cisco Catalyst', 'Enterprise Switch', 'Wired',
 '["9300", "9400", "9500", "9600", "3650", "3850", "2960-X", "2960-XR"]'::jsonb,
 '["802.1X", "MAB", "RADIUS", "TACACS+", "SNMP", "NetConf"]'::jsonb,
 '["CLI", "SNMP", "NetConf", "RESTCONF", "DNA Center"]'::jsonb,
 '{"level": "certified", "features": ["dynamic_vlans", "downloadable_acls", "coa"]}'::jsonb,
 '{"available": true, "count": 20, "types": ["basic", "advanced", "security"]}'::jsonb,
 '["IOS version dependencies", "Feature licensing"]'::jsonb,
 '{"minimum": "16.12", "recommended": "17.3", "latest": "17.9"}'::jsonb,
 '[{"title": "Catalyst Config Guide", "url": "#", "type": "setup"}]'::jsonb,
 'full', 'active', auth.uid()),

('Cisco Meraki', 'Cloud Managed', 'Wireless',
 '["MR46", "MR56", "MR86", "MR46E", "MR57", "MR76", "MR84"]'::jsonb,
 '["802.11ax", "802.11ac", "WPA3-Enterprise", "RADSec", "RADIUS"]'::jsonb,
 '["Dashboard API", "Webhook", "MQTT", "Meraki API"]'::jsonb,
 '{"level": "certified", "features": ["radsec", "dynamic_policies", "splash_integration"]}'::jsonb,
 '{"available": true, "count": 12, "types": ["basic", "guest", "enterprise"]}'::jsonb,
 '["Cloud dependency", "Limited on-premise control"]'::jsonb,
 '{"minimum": "28.6", "recommended": "29.7", "latest": "30.2"}'::jsonb,
 '[{"title": "Meraki Integration Guide", "url": "#", "type": "setup"}]'::jsonb,
 'full', 'active', auth.uid()),

-- Security, MDM, SIEM, and Identity vendors...
('Palo Alto Networks', 'Next-Gen Firewall', 'Security',
 '["PA-220", "PA-820", "PA-3220", "PA-5220", "VM-Series", "CN-Series"]'::jsonb,
 '["User-ID", "GlobalProtect", "WildFire API", "XML API"]'::jsonb,
 '["XML API", "REST API", "User-ID Agent", "Panorama"]'::jsonb,
 '{"level": "certified", "features": ["user_mapping", "dynamic_groups", "threat_intel"]}'::jsonb,
 '{"available": true, "count": 15, "types": ["basic", "advanced", "threat_prevention"]}'::jsonb,
 '["Complex licensing", "High resource requirements"]'::jsonb,
 '{"minimum": "10.1", "recommended": "11.0", "latest": "11.1"}'::jsonb,
 '[{"title": "PAN-OS Integration", "url": "#", "type": "setup"}]'::jsonb,
 'full', 'active', auth.uid()),

('Microsoft Intune', 'Mobile Device Management', 'MDM',
 '["Cloud Service"]'::jsonb,
 '["SCEP", "PKCS", "Azure AD", "Graph API", "Conditional Access"]'::jsonb,
 '["Graph API", "PowerShell", "Azure Logic Apps", "REST API"]'::jsonb,
 '{"level": "certified", "features": ["certificate_deployment", "compliance_sync", "conditional_access"]}'::jsonb,
 '{"available": true, "count": 10, "types": ["basic", "conditional_access", "compliance"]}'::jsonb,
 '["Cloud-only", "Azure AD dependency", "Licensing requirements"]'::jsonb,
 '{"minimum": "N/A", "recommended": "Latest", "latest": "Latest"}'::jsonb,
 '[{"title": "Intune Integration", "url": "#", "type": "setup"}]'::jsonb,
 'full', 'active', auth.uid()),

('Splunk', 'Security Information Event Management', 'SIEM',
 '["Enterprise", "Cloud", "Light"]'::jsonb,
 '["Syslog", "SNMP", "API", "Universal Forwarder"]'::jsonb,
 '["REST API", "SDK", "Universal Forwarder", "HTTP Event Collector"]'::jsonb,
 '{"level": "certified", "features": ["log_ingestion", "correlation", "alerting"]}'::jsonb,
 '{"available": true, "count": 6, "types": ["basic", "advanced", "custom"]}'::jsonb,
 '["High licensing costs", "Resource intensive"]'::jsonb,
 '{"minimum": "8.2", "recommended": "9.0", "latest": "9.1"}'::jsonb,
 '[{"title": "Splunk Integration", "url": "#", "type": "setup"}]'::jsonb,
 'full', 'active', auth.uid()),

('Microsoft Active Directory', 'Directory Services', 'Identity',
 '["Domain Services", "Azure AD", "Azure AD DS"]'::jsonb,
 '["LDAP", "LDAPS", "Kerberos", "NTLM", "SAML"]'::jsonb,
 '["LDAP", "PowerShell", "Graph API", "ADSI"]'::jsonb,
 '{"level": "native", "features": ["user_sync", "group_sync", "authentication"]}'::jsonb,
 '{"available": true, "count": 15, "types": ["basic", "advanced", "hybrid"]}'::jsonb,
 '["Domain trust requirements", "Network connectivity"]'::jsonb,
 '{"minimum": "2012 R2", "recommended": "2019", "latest": "2022"}'::jsonb,
 '[{"title": "AD Integration Guide", "url": "#", "type": "setup"}]'::jsonb,
 'full', 'active', auth.uid());

-- Enhanced requirements library
INSERT INTO requirements_library (title, category, subcategory, priority, requirement_type, description, rationale, acceptance_criteria, verification_methods, test_cases, dependencies, constraints, assumptions, related_use_cases, portnox_features, vendor_requirements, compliance_frameworks, tags, status, created_by) VALUES

-- Technical Requirements
('Active Directory Integration', 'Technical', 'Authentication', 'critical', 'functional',
 'System must integrate with Microsoft Active Directory for user authentication and authorization',
 'Leverage existing identity infrastructure and maintain centralized user management',
 '["Users authenticate with AD credentials", "Group membership synchronized", "LDAP queries <2sec", "Failover support"]'::jsonb,
 '["functional_testing", "performance_testing", "failover_testing"]'::jsonb,
 '["User authentication test", "Group sync test", "Performance test", "Failover test"]'::jsonb,
 '["Active Directory Domain", "Network connectivity", "Service account"]'::jsonb,
 '["Domain trust required", "Firewall rules needed"]'::jsonb,
 '["AD is primary identity source", "Network is stable"]'::jsonb,
 '["User Authentication", "SSO Integration", "Role-Based Access"]'::jsonb,
 '["LDAP Integration", "Group Mapping", "Policy Assignment"]'::jsonb,
 '{"microsoft": {"ad_version": "2012R2+", "forest_level": "2012R2+"}}'::jsonb,
 '{"SOX", "PCI DSS"}'::text[],
 '{"authentication", "ldap", "microsoft", "sso"}'::text[],
 'approved', auth.uid()),

('802.1X Authentication', 'Technical', 'Network Security', 'critical', 'functional',
 'All network access must use 802.1X authentication with certificate-based security',
 'Ensure strong authentication and prevent unauthorized network access',
 '["Certificate-based auth", "EAP-TLS support", "Auto-provisioning", "Revocation checking"]'::jsonb,
 '["security_testing", "certificate_testing", "revocation_testing"]'::jsonb,
 '["EAP-TLS authentication", "Certificate deployment", "Revocation test"]'::jsonb,
 '["PKI Infrastructure", "Certificate templates", "RADIUS server"]'::jsonb,
 '["Certificate lifecycle management", "OCSP/CRL access"]'::jsonb,
 '["PKI is properly configured", "Devices support EAP-TLS"]'::jsonb,
 '["Secure Authentication", "Certificate Management"]'::jsonb,
 '["802.1X Support", "Certificate Deployment", "EAP Methods"]'::jsonb,
 '{"cisco": {"ios_version": "15.2+"}, "aruba": {"clearpass_version": "6.9+"}}'::jsonb,
 '{"PCI DSS", "HIPAA", "SOX"}'::text[],
 '{"802.1x", "certificates", "eap-tls", "pki"}'::text[],
 'approved', auth.uid());

-- Enhanced use case library
INSERT INTO use_case_library (name, category, description, business_value, technical_requirements, prerequisites, test_scenarios, supported_vendors, complexity, estimated_effort, dependencies, implementation_phases, success_metrics, risk_factors, mitigation_strategies, related_requirements, portnox_features, industry_applications, tags, status, created_by) VALUES

('Zero Trust Network Access', 'Authentication', 
 'Implement comprehensive zero-trust network access with continuous verification and risk-based decisions',
 'Reduces security breach risk by 70%, ensures compliance, and provides granular access control',
 '["Multi-factor authentication", "Device compliance", "Continuous monitoring", "Risk engine", "Policy automation"]'::jsonb,
 '["Identity provider", "Device management", "Certificate infrastructure", "SIEM integration"]'::jsonb,
 '["MFA authentication", "Device compliance check", "Risk-based access", "Policy enforcement"]'::jsonb,
 '["Portnox", "Microsoft", "Okta", "Palo Alto"]'::jsonb,
 'high', '12-16 weeks',
 '["Active Directory", "PKI", "Device Management", "SIEM"]'::jsonb,
 '["Phase 1: Identity integration", "Phase 2: Device compliance", "Phase 3: Risk engine", "Phase 4: Full automation"]'::jsonb,
 '["Authentication success rate >99%", "Mean time to access <30s", "Security incidents <5/month"]'::jsonb,
 '["Complex integration", "User resistance", "Performance impact"]'::jsonb,
 '["Phased rollout", "User training", "Performance monitoring"]'::jsonb,
 '["Active Directory Integration", "802.1X Authentication", "Device Compliance"]'::jsonb,
 '["Risk-based Authentication", "Continuous Monitoring", "Policy Automation"]'::jsonb,
 '["Financial Services", "Healthcare", "Government", "Critical Infrastructure"]'::jsonb,
 '{"zero-trust", "mfa", "risk-based", "continuous"}'::text[],
 'approved', auth.uid()),

('IoT Device Security', 'IoT Security',
 'Automated secure onboarding, management, and monitoring of IoT devices with micro-segmentation',
 'Enables secure IoT deployment while maintaining network security and compliance',
 '["Device discovery", "Certificate provisioning", "Micro-segmentation", "Behavioral monitoring"]'::jsonb,
 '["PKI infrastructure", "Network segmentation", "Device inventory", "Monitoring platform"]'::jsonb,
 '["Auto-discovery", "Certificate deployment", "Policy enforcement", "Anomaly detection"]'::jsonb,
 '["Portnox", "Cisco ISE", "Aruba ClearPass"]'::jsonb,
 'medium', '8-12 weeks',
 '["PKI", "Network Infrastructure", "Monitoring Tools"]'::jsonb,
 '["Phase 1: Discovery setup", "Phase 2: Certificate deployment", "Phase 3: Segmentation", "Phase 4: Monitoring"]'::jsonb,
 '["Device onboarding time <5min", "Security incidents 0", "Network performance maintained"]'::jsonb,
 '["Device diversity", "Certificate lifecycle", "Network complexity"]'::jsonb,
 '["Device classification", "Automated certificate renewal", "Network documentation"]'::jsonb,
 '["Device Auto-Discovery", "Certificate Management", "Network Segmentation"]'::jsonb,
 '["IoT Profiling", "Certificate Deployment", "Micro-segmentation"]'::jsonb,
 '["Manufacturing", "Healthcare", "Smart Buildings", "Retail"]'::jsonb,
 '{"iot", "certificates", "segmentation", "automation"}'::text[],
 'approved', auth.uid());