-- Add comprehensive vendor library for networking, security, and compliance
INSERT INTO vendor_library (vendor_name, category, support_level, integration_status, documentation_links, is_verified, vendor_specific_features, supported_features, created_by) VALUES
-- Networking Wired Vendors
('Aruba Networks', 'wired_networking', 'full', 'native', '["https://www.arubanetworks.com/support/"]', true, '{"clearpass_integration": true, "policy_enforcement": true, "dynamic_segmentation": true}', '["802.1X", "MAB", "Dynamic VLAN", "User Role Assignment"]', '00000000-0000-0000-0000-000000000000'),
('Extreme Networks', 'wired_networking', 'full', 'native', '["https://extremenetworks.com/support/"]', true, '{"nac_integration": true, "fabric_connect": true}', '["802.1X", "MAB", "LLDP-MED", "Fabric Attach"]', '00000000-0000-0000-0000-000000000000'),
('Juniper Networks', 'wired_networking', 'full', 'native', '["https://www.juniper.net/support/"]', true, '{"pulse_secure": true, "mist_ai": true}', '["802.1X", "MAB", "EX Series Integration", "Junos Pulse"]', '00000000-0000-0000-0000-000000000000'),
('Huawei', 'wired_networking', 'partial', 'api', '["https://support.huawei.com/"]', true, '{"cloudengine": true, "agile_controller": true}', '["802.1X", "MAB", "HWTACACS"]', '00000000-0000-0000-0000-000000000000'),
('Dell Technologies', 'wired_networking', 'full', 'native', '["https://www.dell.com/support/"]', true, '{"os10_integration": true, "powerswitch": true}', '["802.1X", "MAB", "LLDP", "OS10 Management"]', '00000000-0000-0000-0000-000000000000'),

-- Networking Wireless Vendors
('Aruba Wireless', 'wireless_networking', 'full', 'native', '["https://www.arubanetworks.com/support/"]', true, '{"instant_on": true, "central_cloud": true, "clearpass_integration": true}', '["WiFi 6E", "802.1X", "WPA3", "Dynamic VLAN"]', '00000000-0000-0000-0000-000000000000'),
('Ruckus Networks', 'wireless_networking', 'full', 'native', '["https://support.ruckuswireless.com/"]', true, '{"smartzone": true, "unleashed": true}', '["WiFi 6", "802.1X", "DPSK", "BeamFlex"]', '00000000-0000-0000-0000-000000000000'),
('Meraki', 'wireless_networking', 'full', 'api', '["https://documentation.meraki.com/"]', true, '{"cloud_managed": true, "dashboard_api": true}', '["WiFi 6", "802.1X", "Splash Pages", "Group Policies"]', '00000000-0000-0000-0000-000000000000'),
('Ubiquiti', 'wireless_networking', 'partial', 'api', '["https://help.ui.com/"]', true, '{"unifi_controller": true, "dream_machine": true}', '["WiFi 6", "VLAN", "Guest Portal", "UniFi Network"]', '00000000-0000-0000-0000-000000000000'),
('Mist (Juniper)', 'wireless_networking', 'full', 'native', '["https://www.mist.com/support/"]', true, '{"ai_driven": true, "cloud_native": true}', '["WiFi 6E", "AI Insights", "Location Services", "Marvis AI"]', '00000000-0000-0000-0000-000000000000'),

-- Firewall Vendors
('Palo Alto Networks', 'firewall', 'full', 'api', '["https://docs.paloaltonetworks.com/"]', true, '{"globalprotect": true, "prisma_access": true, "user_id": true}', '["Next-Gen Firewall", "User-ID", "GlobalProtect", "Threat Prevention"]', '00000000-0000-0000-0000-000000000000'),
('Fortinet', 'firewall', 'full', 'api', '["https://docs.fortinet.com/"]', true, '{"fortigate": true, "fortios": true, "security_fabric": true}', '["NGFW", "SD-WAN", "ZTNA", "Security Fabric"]', '00000000-0000-0000-0000-000000000000'),
('Check Point', 'firewall', 'full', 'api', '["https://supportcenter.checkpoint.com/"]', true, '{"smartconsole": true, "harmony": true}', '["Infinity Architecture", "SmartConsole", "Harmony", "CloudGuard"]', '00000000-0000-0000-0000-000000000000'),
('SonicWall', 'firewall', 'partial', 'api', '["https://www.sonicwall.com/support/"]', true, '{"sonicwallnsa": true, "capture_security": true}', '["NGFW", "Capture Security", "SSL VPN", "WAN Acceleration"]', '00000000-0000-0000-0000-000000000000'),
('pfSense', 'firewall', 'partial', 'manual', '["https://docs.netgate.com/"]', true, '{"open_source": true, "community": true}', '["Open Source", "pfBlocker", "Snort", "Community Packages"]', '00000000-0000-0000-0000-000000000000'),

-- IDP (Identity Provider) Vendors  
('Active Directory', 'idp', 'full', 'native', '["https://docs.microsoft.com/en-us/windows-server/identity/"]', true, '{"domain_services": true, "certificate_services": true, "federation": true}', '["LDAP", "Kerberos", "NTLM", "ADFS"]', '00000000-0000-0000-0000-000000000000'),
('Azure Active Directory', 'idp', 'full', 'api', '["https://docs.microsoft.com/en-us/azure/active-directory/"]', true, '{"conditional_access": true, "mfa": true, "hybrid_identity": true}', '["SAML", "OAuth", "OpenID Connect", "Conditional Access"]', '00000000-0000-0000-0000-000000000000'),
('Okta', 'idp', 'full', 'api', '["https://developer.okta.com/"]', true, '{"universal_directory": true, "adaptive_mfa": true}', '["SAML", "OAuth", "SCIM", "Adaptive MFA"]', '00000000-0000-0000-0000-000000000000'),
('Ping Identity', 'idp', 'full', 'api', '["https://docs.pingidentity.com/"]', true, '{"pingfederate": true, "pingdirectory": true}', '["SAML", "OAuth", "OpenID Connect", "Risk-based Auth"]', '00000000-0000-0000-0000-000000000000'),
('OneLogin', 'idp', 'full', 'api', '["https://developers.onelogin.com/"]', true, '{"smartfactor": true, "desktop_sso": true}', '["SAML", "OAuth", "RADIUS", "SmartFactor MFA"]', '00000000-0000-0000-0000-000000000000'),

-- MDM Vendors
('Microsoft Intune', 'mdm', 'full', 'api', '["https://docs.microsoft.com/en-us/mem/intune/"]', true, '{"autopilot": true, "compliance_policies": true, "conditional_access": true}', '["Device Compliance", "App Protection", "Conditional Access", "Autopilot"]', '00000000-0000-0000-0000-000000000000'),
('VMware Workspace ONE', 'mdm', 'full', 'api', '["https://docs.vmware.com/en/VMware-Workspace-ONE/"]', true, '{"uem": true, "workspace_intelligence": true}', '["UEM", "App Management", "Content Collaboration", "Analytics"]', '00000000-0000-0000-0000-000000000000'),
('Jamf', 'mdm', 'full', 'api', '["https://developer.jamf.com/"]', true, '{"jamf_pro": true, "jamf_protect": true, "apple_focus": true}', '["Apple Management", "Zero-Touch Deployment", "Threat Defense"]', '00000000-0000-0000-0000-000000000000'),
('MobileIron', 'mdm', 'partial', 'api', '["https://docs.mobileiron.com/"]', true, '{"core_connector": true, "tunnel": true}', '["Device Management", "App Wrapping", "Secure Connectivity"]', '00000000-0000-0000-0000-000000000000'),
('Citrix Endpoint Management', 'mdm', 'full', 'api', '["https://docs.citrix.com/"]', true, '{"secure_mail": true, "secure_web": true}', '["Device Management", "App Management", "Secure Productivity"]', '00000000-0000-0000-0000-000000000000'),

-- EDR Vendors
('CrowdStrike Falcon', 'edr', 'full', 'api', '["https://falcon.crowdstrike.com/support/"]', true, '{"threat_graph": true, "real_time_response": true, "threat_hunting": true}', '["Endpoint Detection", "Threat Hunting", "Incident Response", "Cloud Workload Protection"]', '00000000-0000-0000-0000-000000000000'),
('SentinelOne', 'edr', 'full', 'api', '["https://support.sentinelone.com/"]', true, '{"singularity_platform": true, "autonomous_response": true}', '["AI-Powered Detection", "Autonomous Response", "Threat Hunting", "Rollback"]', '00000000-0000-0000-0000-000000000000'),
('Microsoft Defender for Endpoint', 'edr', 'full', 'api', '["https://docs.microsoft.com/en-us/microsoft-365/security/"]', true, '{"threat_vulnerability": true, "attack_surface_reduction": true}', '["Behavioral Analysis", "Cloud Detection", "Automated Investigation", "Threat Analytics"]', '00000000-0000-0000-0000-000000000000'),
('Carbon Black (VMware)', 'edr', 'full', 'api', '["https://docs.vmware.com/en/VMware-Carbon-Black/"]', true, '{"cb_cloud": true, "cb_defense": true}', '["Endpoint Standard", "Endpoint Advanced", "Audit and Remediation"]', '00000000-0000-0000-0000-000000000000'),
('Cylance (BlackBerry)', 'edr', 'partial', 'api', '["https://docs.blackberry.com/en/endpoint-management/"]', true, '{"ai_prevention": true, "optics": true}', '["AI Prevention", "EDR", "Memory Protection", "Script Control"]', '00000000-0000-0000-0000-000000000000'),

-- SIEM Vendors
('Splunk', 'siem', 'full', 'api', '["https://docs.splunk.com/"]', true, '{"enterprise_security": true, "phantom": true, "ueba": true}', '["Log Management", "Security Analytics", "SOAR", "UEBA"]', '00000000-0000-0000-0000-000000000000'),
('IBM QRadar', 'siem', 'full', 'api', '["https://www.ibm.com/support/knowledgecenter/SS42VS"]', true, '{"risk_manager": true, "incident_forensics": true}', '["Security Intelligence", "Network Insights", "Risk Management", "Incident Forensics"]', '00000000-0000-0000-0000-000000000000'),
('Microsoft Sentinel', 'siem', 'full', 'api', '["https://docs.microsoft.com/en-us/azure/sentinel/"]', true, '{"cloud_native": true, "ai_ml": true, "soar": true}', '["Cloud-Native SIEM", "AI/ML Analytics", "SOAR", "Threat Intelligence"]', '00000000-0000-0000-0000-000000000000'),
('LogRhythm', 'siem', 'full', 'api', '["https://docs.logrhythm.com/"]', true, '{"nexgen_siem": true, "resolvr": true}', '["NextGen SIEM", "UEBA", "SOAR", "Threat Lifecycle Management"]', '00000000-0000-0000-0000-000000000000'),
('ArcSight (Micro Focus)', 'siem', 'partial', 'api', '["https://www.microfocus.com/documentation/arcsight/"]', true, '{"esm": true, "intelligence": true}', '["Enterprise Security Manager", "Threat Intelligence", "Risk Analytics"]', '00000000-0000-0000-0000-000000000000');

-- Add comprehensive use cases
INSERT INTO use_case_library (title, category, priority, description, business_value, technical_requirements, implementation_complexity, estimated_timeline, success_metrics, created_by) VALUES
-- Security Use Cases
('Zero Trust Network Access', 'security', 'high', 'Implement zero trust architecture with continuous verification of all users and devices', 'Reduces security breaches by 70%, improves compliance posture', '["NAC Solution", "MFA", "Device Compliance", "Risk Assessment"]', 'high', '3-6 months', '["Reduced security incidents", "100% device visibility", "Policy compliance rate >95%"]', '00000000-0000-0000-0000-000000000000'),
('BYOD Security Framework', 'security', 'high', 'Secure bring-your-own-device program with automated onboarding and compliance', 'Increases employee satisfaction while maintaining security', '["MDM Integration", "Certificate Management", "Guest Network", "Policy Engine"]', 'medium', '2-4 months', '["Device enrollment rate >90%", "Security incident reduction", "User satisfaction score >4.5"]', '00000000-0000-0000-0000-000000000000'),
('IoT Device Management', 'security', 'medium', 'Automated discovery, classification, and security policy enforcement for IoT devices', 'Reduces IoT-related security risks and improves operational visibility', '["Device Fingerprinting", "Network Segmentation", "Behavior Analytics", "Policy Automation"]', 'high', '4-8 months', '["100% IoT device visibility", "Automated policy enforcement", "Reduced manual overhead"]', '00000000-0000-0000-0000-000000000000'),
('Compliance Automation', 'compliance', 'high', 'Automated compliance reporting and audit trail for regulatory requirements', 'Reduces audit preparation time by 80%, ensures continuous compliance', '["Audit Logging", "Report Generation", "Policy Templates", "Risk Assessment"]', 'medium', '2-3 months', '["Audit readiness time <1 week", "Compliance score >95%", "Automated reporting"]', '00000000-0000-0000-0000-000000000000'),

-- Operational Use Cases
('Automated Guest Access', 'operations', 'medium', 'Self-service guest registration with automatic provisioning and time-limited access', 'Improves visitor experience while maintaining security controls', '["Self-Service Portal", "SMS/Email Integration", "Time-Based Policies", "Sponsor Approval"]', 'low', '1-2 months', '["Guest satisfaction >4.0", "IT request reduction >50%", "Security policy compliance"]', '00000000-0000-0000-0000-000000000000'),
('Network Troubleshooting', 'operations', 'medium', 'Automated network issue detection and resolution with detailed forensics', 'Reduces MTTR by 60%, improves network availability', '["Real-time Monitoring", "Event Correlation", "Automated Remediation", "Forensic Analysis"]', 'medium', '2-3 months', '["MTTR reduction >60%", "Network uptime >99.5%", "Automated issue resolution >40%"]', '00000000-0000-0000-0000-000000000000'),
('Bandwidth Optimization', 'operations', 'low', 'Dynamic bandwidth allocation based on user roles and application priorities', 'Improves application performance and user experience', '["QoS Integration", "Application Recognition", "Dynamic Policies", "Usage Analytics"]', 'medium', '2-4 months', '["Application response time improvement", "Bandwidth utilization optimization", "User satisfaction increase"]', '00000000-0000-0000-0000-000000000000'),

-- Industry-Specific Use Cases  
('Healthcare HIPAA Compliance', 'healthcare', 'high', 'HIPAA-compliant network access with PHI protection and audit trails', 'Ensures regulatory compliance and protects patient data', '["Encryption", "Audit Logging", "Role-Based Access", "Risk Assessment"]', 'high', '3-6 months', '["HIPAA compliance certification", "Zero PHI breaches", "Audit trail completeness"]', '00000000-0000-0000-0000-000000000000'),
('Financial PCI DSS Compliance', 'finance', 'high', 'PCI DSS compliant network segmentation and cardholder data protection', 'Maintains payment card industry compliance and customer trust', '["Network Segmentation", "Encryption", "Access Controls", "Monitoring"]', 'high', '4-8 months', '["PCI DSS certification", "Cardholder data protection", "Compliance audit pass"]', '00000000-0000-0000-0000-000000000000'),
('Educational Campus Security', 'education', 'medium', 'Multi-tenant network access for students, faculty, and guests with appropriate controls', 'Balances open access with security requirements', '["Multi-Tenancy", "Guest Access", "Content Filtering", "Usage Monitoring"]', 'medium', '2-4 months', '["User satisfaction >4.0", "Security incident reduction", "Policy compliance >90%"]', '00000000-0000-0000-0000-000000000000'),
('Manufacturing OT Security', 'manufacturing', 'high', 'Operational technology network security with minimal disruption to production', 'Protects critical infrastructure while maintaining operational continuity', '["OT/IT Segmentation", "Asset Discovery", "Anomaly Detection", "Production Continuity"]', 'high', '6-12 months', '["Zero production disruptions", "OT asset visibility", "Cyber threat reduction"]', '00000000-0000-0000-0000-000000000000');

-- Add comprehensive requirements
INSERT INTO requirements_library (title, category, description, acceptance_criteria, business_justification, technical_specifications, dependencies, risk_level, implementation_effort, created_by) VALUES
-- Functional Requirements
('Multi-Factor Authentication', 'authentication', 'All network access must require multi-factor authentication for enhanced security', 'MFA required for all users, support for multiple MFA methods, integration with existing identity providers', 'Reduces password-related breaches by 99.9%, meets compliance requirements', '{"supported_methods": ["TOTP", "SMS", "Push", "Biometric"], "integration": ["AD", "Azure AD", "Okta"], "fallback": "Emergency codes"}', '["Identity Provider", "Mobile Device Management"]', 'low', 'medium', '00000000-0000-0000-0000-000000000000'),
('Device Compliance Checking', 'security', 'Automated verification of device compliance before network access', 'Real-time compliance checking, automated remediation, reporting capabilities', 'Prevents non-compliant devices from accessing sensitive resources', '{"checks": ["Antivirus", "OS Updates", "Encryption", "Certificate"], "enforcement": "Block non-compliant", "remediation": "Automated"}', '["MDM Solution", "Certificate Authority"]', 'medium', 'high', '00000000-0000-0000-0000-000000000000'),
('Network Segmentation', 'network', 'Dynamic network segmentation based on user roles and device types', 'Automated VLAN assignment, microsegmentation capabilities, policy enforcement', 'Limits blast radius of security incidents, improves network performance', '{"segmentation": "Dynamic", "granularity": "User/Device based", "enforcement": "Real-time", "scalability": "Enterprise"}', '["VLAN Infrastructure", "Policy Engine"]', 'high', 'high', '00000000-0000-0000-0000-000000000000'),
('Guest Access Management', 'operations', 'Self-service guest access with automated provisioning and monitoring', 'Self-service portal, sponsor approval workflow, time-limited access, usage monitoring', 'Improves visitor experience while maintaining security controls', '{"portal": "Self-service", "approval": "Sponsor-based", "duration": "Time-limited", "monitoring": "Real-time"}', '["Web Portal", "Email/SMS Gateway"]', 'low', 'low', '00000000-0000-0000-0000-000000000000'),

-- Non-Functional Requirements
('High Availability', 'infrastructure', '99.9% uptime with redundancy and failover capabilities', 'Less than 8.76 hours downtime per year, automatic failover, no single points of failure', 'Ensures business continuity and user productivity', '{"uptime": "99.9%", "failover": "Automatic", "redundancy": "N+1", "monitoring": "24/7"}', '["Redundant Infrastructure", "Load Balancing"]', 'high', 'high', '00000000-0000-0000-0000-000000000000'),
('Scalability', 'performance', 'Support for 10,000+ concurrent users with linear performance scaling', 'Performance testing validated, horizontal scaling capability, resource optimization', 'Accommodates business growth without performance degradation', '{"capacity": "10,000+ users", "scaling": "Horizontal", "performance": "Linear", "optimization": "Automatic"}', '["Scalable Architecture", "Performance Monitoring"]', 'medium', 'high', '00000000-0000-0000-0000-000000000000'),
('Audit and Compliance', 'compliance', 'Comprehensive logging and reporting for regulatory compliance', 'Complete audit trail, automated reporting, data retention policies, compliance dashboards', 'Meets regulatory requirements and reduces audit preparation time', '{"logging": "Comprehensive", "retention": "7 years", "reports": "Automated", "compliance": "SOX/HIPAA/PCI"}', '["Log Management", "Report Engine"]', 'medium', 'medium', '00000000-0000-0000-0000-000000000000'),

-- Integration Requirements
('SIEM Integration', 'integration', 'Real-time security event forwarding to SIEM platforms', 'Real-time event streaming, standardized log format, threat intelligence correlation', 'Enhances security operations center capabilities and incident response', '{"streaming": "Real-time", "format": "CEF/LEEF/JSON", "protocols": ["Syslog", "HTTPS", "Kafka"], "enrichment": "Context-aware"}', '["SIEM Platform", "Network Connectivity"]', 'low', 'medium', '00000000-0000-0000-0000-000000000000'),
('Identity Provider Sync', 'integration', 'Automated synchronization with enterprise identity providers', 'Real-time user/group sync, attribute mapping, error handling and recovery', 'Ensures consistent access policies and reduces administrative overhead', '{"sync": "Real-time", "protocols": ["LDAP", "SCIM", "Graph API"], "mapping": "Flexible", "recovery": "Automatic"}', '["Identity Provider", "Directory Services"]', 'medium', 'medium', '00000000-0000-0000-0000-000000000000'),
('Cloud Integration', 'integration', 'Hybrid cloud support with cloud-native integrations', 'Multi-cloud support, API-first architecture, cloud-native scaling', 'Enables modern cloud architectures and hybrid deployments', '{"clouds": ["AWS", "Azure", "GCP"], "architecture": "API-first", "scaling": "Cloud-native", "management": "Unified"}', '["Cloud Platform", "API Gateway"]', 'medium', 'high', '00000000-0000-0000-0000-000000000000');

-- Update existing vendors with AI-editable fields
UPDATE vendor_library 
SET vendor_specific_features = COALESCE(vendor_specific_features, '{}'::jsonb) || jsonb_build_object(
  'ai_updatable_fields', array['firmware_versions', 'supported_protocols', 'authentication_methods', 'security_features'],
  'last_ai_update', null,
  'ai_confidence_score', 0.0,
  'auto_update_enabled', false
),
tags = COALESCE(tags, '[]'::jsonb) || jsonb_build_array('ai_managed', 'enterprise', 'production_ready')
WHERE vendor_name IN ('Cisco', 'Aruba Networks', 'Microsoft', 'Fortinet', 'Palo Alto Networks');