-- Enhanced vendor library with comprehensive data
INSERT INTO vendor_library (vendor_name, vendor_type, category, models, supported_protocols, integration_methods, portnox_compatibility, configuration_templates, known_limitations, firmware_requirements, documentation_links, support_level, status, created_by) VALUES

-- NAC Vendors
('Portnox', 'Network Access Control', 'NAC', 
 '["CORE", "CLEAR", "EDGE", "Cloud"]'::jsonb,
 '["RADIUS", "802.1X", "MAB", "TACACS+", "LDAP", "SAML"]'::jsonb,
 '["Native API", "REST API", "SAML SSO", "SCIM"]'::jsonb,
 '{"level": "native", "features": ["full_integration", "advanced_policies", "real_time_sync"]}'::jsonb,
 '{"available": true, "count": 25, "types": ["basic", "advanced", "industry_specific"]}'::jsonb,
 '[]'::jsonb,
 '{"minimum": "21.1", "recommended": "23.1", "latest": "23.5"}'::jsonb,
 '[{"title": "Admin Guide", "url": "https://docs.portnox.com", "type": "setup"}, {"title": "API Reference", "url": "https://api.portnox.com", "type": "api"}]'::jsonb,
 'full', 'active', auth.uid()),

-- Cisco Products
('Cisco ISE', 'Identity Services Engine', 'NAC',
 '["3355", "3365", "3375", "3395", "Virtual", "SNS-3415", "SNS-3495"]'::jsonb,
 '["RADIUS", "TACACS+", "802.1X", "MAB", "EAP-TLS", "PEAP", "EAP-TTLS"]'::jsonb,
 '["pxGrid", "REST API", "SDK", "ERS API"]'::jsonb,
 '{"level": "certified", "features": ["policy_sync", "threat_sharing", "context_sharing"]}'::jsonb,
 '{"available": true, "count": 15, "types": ["basic", "advanced"]}'::jsonb,
 '["Complex licensing", "High resource requirements"]'::jsonb,
 '{"minimum": "3.0", "recommended": "3.2", "latest": "3.3"}'::jsonb,
 '[{"title": "ISE Integration Guide", "url": "#", "type": "setup"}]'::jsonb,
 'full', 'active', auth.uid()),

('Cisco Catalyst', 'Enterprise Switch', 'Wired',
 '["9300", "9400", "9500", "9600", "3650", "3850", "2960-X", "2960-XR"]'::jsonb,
 '["802.1X", "MAB", "RADIUS", "TACACS+", "SNMP", "NetConf"]'::jsonb,
 '["CLI", "SNMP", "NetConf", "RESTCONF", "DNA Center"]'::jsonb,
 '{"level": "certified", "features": ["dynamic_vlans", "downloadable_acls", "coa"]}'::jsonb,
 '{"available": true, "count": 20, "types": ["basic", "advanced", "security"]}'::jsonb,
 '["IOS version dependencies", "Feature licensing"]'::jsonb,
 '{"minimum": "16.12", "recommended": "17.3", "latest": "17.9"}'::jsonb,
 '[{"title": "Catalyst Config Guide", "url": "#", "type": "setup"}]'::jsonb,
 'full', 'active', auth.uid()),

('Cisco Meraki', 'Cloud Managed', 'Wireless',
 '["MR46", "MR56", "MR86", "MR46E", "MR57", "MR76", "MR84"]'::jsonb,
 '["802.11ax", "802.11ac", "WPA3-Enterprise", "RADSec", "RADIUS"]'::jsonb,
 '["Dashboard API", "Webhook", "MQTT", "Meraki API"]'::jsonb,
 '{"level": "certified", "features": ["radsec", "dynamic_policies", "splash_integration"]}'::jsonb,
 '{"available": true, "count": 12, "types": ["basic", "guest", "enterprise"]}'::jsonb,
 '["Cloud dependency", "Limited on-premise control"]'::jsonb,
 '{"minimum": "28.6", "recommended": "29.7", "latest": "30.2"}'::jsonb,
 '[{"title": "Meraki Integration Guide", "url": "#", "type": "setup"}]'::jsonb,
 'full', 'active', auth.uid()),

-- Aruba Products
('Aruba ClearPass', 'Policy Management Platform', 'NAC',
 '["C1000", "C2500", "C3000", "C5000", "Virtual"]'::jsonb,
 '["RADIUS", "TACACS+", "802.1X", "MAB", "EAP-TLS", "PEAP"]'::jsonb,
 '["REST API", "XML API", "SDK", "WebAuth"]'::jsonb,
 '{"level": "certified", "features": ["policy_sync", "user_sync", "device_sync"]}'::jsonb,
 '{"available": true, "count": 18, "types": ["basic", "advanced", "guest"]}'::jsonb,
 '["License limitations", "Hardware dependencies"]'::jsonb,
 '{"minimum": "6.9", "recommended": "6.11", "latest": "6.12"}'::jsonb,
 '[{"title": "ClearPass Integration", "url": "#", "type": "setup"}]'::jsonb,
 'full', 'active', auth.uid()),

('Aruba Instant On', 'Small Business Wireless', 'Wireless',
 '["AP11", "AP11D", "AP12", "AP15", "AP17", "AP22"]'::jsonb,
 '["WPA3", "WPA2-Enterprise", "802.1X", "RADIUS"]'::jsonb,
 '["Cloud API", "Mobile App", "Web Interface"]'::jsonb,
 '{"level": "basic", "features": ["radius_auth", "vlan_assignment"]}'::jsonb,
 '{"available": true, "count": 8, "types": ["basic", "guest"]}'::jsonb,
 '["Limited enterprise features", "Cloud dependency"]'::jsonb,
 '{"minimum": "8.7", "recommended": "8.10", "latest": "8.12"}'::jsonb,
 '[{"title": "Instant On Setup", "url": "#", "type": "setup"}]'::jsonb,
 'partial', 'active', auth.uid()),

-- Security Vendors
('Palo Alto Networks', 'Next-Gen Firewall', 'Security',
 '["PA-220", "PA-820", "PA-3220", "PA-5220", "VM-Series", "CN-Series"]'::jsonb,
 '["User-ID", "GlobalProtect", "WildFire API", "XML API"]'::jsonb,
 '["XML API", "REST API", "User-ID Agent", "Panorama"]'::jsonb,
 '{"level": "certified", "features": ["user_mapping", "dynamic_groups", "threat_intel"]}'::jsonb,
 '{"available": true, "count": 15, "types": ["basic", "advanced", "threat_prevention"]}'::jsonb,
 '["Complex licensing", "High resource requirements"]'::jsonb,
 '{"minimum": "10.1", "recommended": "11.0", "latest": "11.1"}'::jsonb,
 '[{"title": "PAN-OS Integration", "url": "#", "type": "setup"}]'::jsonb,
 'full', 'active', auth.uid()),

('Fortinet FortiGate', 'Unified Threat Management', 'Security',
 '["60F", "80F", "100F", "200F", "400F", "600F", "VM"]'::jsonb,
 '["RADIUS", "LDAP", "SAML", "FortiAuthenticator"]'::jsonb,
 '["REST API", "CLI", "SNMP", "FortiManager"]'::jsonb,
 '{"level": "certified", "features": ["user_auth", "policy_enforcement", "ssl_inspection"]}'::jsonb,
 '{"available": true, "count": 12, "types": ["basic", "advanced", "utm"]}'::jsonb,
 '["Feature licensing", "Performance impact"]'::jsonb,
 '{"minimum": "7.0", "recommended": "7.2", "latest": "7.4"}'::jsonb,
 '[{"title": "FortiGate Integration", "url": "#", "type": "setup"}]'::jsonb,
 'full', 'active', auth.uid()),

-- MDM Vendors
('Microsoft Intune', 'Mobile Device Management', 'MDM',
 '["Cloud Service"]'::jsonb,
 '["SCEP", "PKCS", "Azure AD", "Graph API", "Conditional Access"]'::jsonb,
 '["Graph API", "PowerShell", "Azure Logic Apps", "REST API"]'::jsonb,
 '{"level": "certified", "features": ["certificate_deployment", "compliance_sync", "conditional_access"]}'::jsonb,
 '{"available": true, "count": 10, "types": ["basic", "conditional_access", "compliance"]}'::jsonb,
 '["Cloud-only", "Azure AD dependency", "Licensing requirements"]'::jsonb,
 '{"minimum": "N/A", "recommended": "Latest", "latest": "Latest"}'::jsonb,
 '[{"title": "Intune Integration", "url": "#", "type": "setup"}]'::jsonb,
 'full', 'active', auth.uid()),

('VMware Workspace ONE', 'Unified Endpoint Management', 'MDM',
 '["Cloud", "On-Premises"]'::jsonb,
 '["SCEP", "PKCS", "LDAP", "SAML", "OAuth"]'::jsonb,
 '["REST API", "PowerShell", "AirWatch API"]'::jsonb,
 '{"level": "certified", "features": ["certificate_management", "app_deployment", "compliance"]}'::jsonb,
 '{"available": true, "count": 8, "types": ["basic", "advanced", "compliance"]}'::jsonb,
 '["Complex licensing", "Migration complexity"]'::jsonb,
 '{"minimum": "21.05", "recommended": "22.09", "latest": "23.06"}'::jsonb,
 '[{"title": "Workspace ONE Integration", "url": "#", "type": "setup"}]'::jsonb,
 'full', 'active', auth.uid()),

-- SIEM Vendors
('Splunk', 'Security Information Event Management', 'SIEM',
 '["Enterprise", "Cloud", "Light"]'::jsonb,
 '["Syslog", "SNMP", "API", "Universal Forwarder"]'::jsonb,
 '["REST API", "SDK", "Universal Forwarder", "HTTP Event Collector"]'::jsonb,
 '{"level": "certified", "features": ["log_ingestion", "correlation", "alerting"]}'::jsonb,
 '{"available": true, "count": 6, "types": ["basic", "advanced", "custom"]}'::jsonb,
 '["High licensing costs", "Resource intensive"]'::jsonb,
 '{"minimum": "8.2", "recommended": "9.0", "latest": "9.1"}'::jsonb,
 '[{"title": "Splunk Integration", "url": "#", "type": "setup"}]'::jsonb,
 'full', 'active', auth.uid()),

('IBM QRadar', 'Security Intelligence Platform', 'SIEM',
 '["Physical", "Virtual", "Cloud"]'::jsonb,
 '["Syslog", "SNMP", "WinCollect", "Log Sources"]'::jsonb,
 '["REST API", "CLI", "STIX/TAXII", "Ariel API"]'::jsonb,
 '{"level": "certified", "features": ["threat_detection", "incident_response", "compliance"]}'::jsonb,
 '{"available": true, "count": 5, "types": ["basic", "advanced"]}'::jsonb,
 '["Complex deployment", "Expensive licensing"]'::jsonb,
 '{"minimum": "7.4", "recommended": "7.5", "latest": "7.5.0"}'::jsonb,
 '[{"title": "QRadar Integration", "url": "#", "type": "setup"}]'::jsonb,
 'full', 'active', auth.uid()),

-- Identity Providers
('Microsoft Active Directory', 'Directory Services', 'Identity',
 '["Domain Services", "Azure AD", "Azure AD DS"]'::jsonb,
 '["LDAP", "LDAPS", "Kerberos", "NTLM", "SAML"]'::jsonb,
 '["LDAP", "PowerShell", "Graph API", "ADSI"]'::jsonb,
 '{"level": "native", "features": ["user_sync", "group_sync", "authentication"]}'::jsonb,
 '{"available": true, "count": 15, "types": ["basic", "advanced", "hybrid"]}'::jsonb,
 '["Domain trust requirements", "Network connectivity"]'::jsonb,
 '{"minimum": "2012 R2", "recommended": "2019", "latest": "2022"}'::jsonb,
 '[{"title": "AD Integration Guide", "url": "#", "type": "setup"}]'::jsonb,
 'full', 'active', auth.uid()),

('Okta', 'Identity and Access Management', 'Identity',
 '["Cloud", "On-Premises Agent"]'::jsonb,
 '["SAML", "OAuth", "OpenID Connect", "LDAP", "RADIUS"]'::jsonb,
 '["REST API", "SCIM", "Hooks", "Event Hooks"]'::jsonb,
 '{"level": "certified", "features": ["sso", "provisioning", "mfa"]}'::jsonb,
 '{"available": true, "count": 10, "types": ["basic", "advanced", "adaptive"]}'::jsonb,
 '["Cloud dependency", "Licensing costs"]'::jsonb,
 '{"minimum": "N/A", "recommended": "Latest", "latest": "Latest"}'::jsonb,
 '[{"title": "Okta Integration", "url": "#", "type": "setup"}]'::jsonb,
 'full', 'active', auth.uid());

-- Enhanced requirements library
INSERT INTO requirements_library (title, category, subcategory, priority, requirement_type, description, rationale, acceptance_criteria, verification_methods, test_cases, dependencies, constraints, assumptions, related_use_cases, portnox_features, vendor_requirements, compliance_frameworks, tags, status, created_by) VALUES

-- Technical Requirements
('Active Directory Integration', 'Technical', 'Authentication', 'critical', 'functional',
 'System must integrate with Microsoft Active Directory for user authentication and authorization',
 'Leverage existing identity infrastructure and maintain centralized user management',
 '["Users authenticate with AD credentials", "Group membership synchronized", "LDAP queries <2sec", "Failover support"]'::jsonb,
 '["functional_testing", "performance_testing", "failover_testing"]'::jsonb,
 '["User authentication test", "Group sync test", "Performance test", "Failover test"]'::jsonb,
 '["Active Directory Domain", "Network connectivity", "Service account"]'::jsonb,
 '["Domain trust required", "Firewall rules needed"]'::jsonb,
 '["AD is primary identity source", "Network is stable"]'::jsonb,
 '["User Authentication", "SSO Integration", "Role-Based Access"]'::jsonb,
 '["LDAP Integration", "Group Mapping", "Policy Assignment"]'::jsonb,
 '{"microsoft": {"ad_version": "2012R2+", "forest_level": "2012R2+"}}'::jsonb,
 '["SOX", "PCI DSS"]'::jsonb,
 '["authentication", "ldap", "microsoft", "sso"]'::jsonb,
 'approved', auth.uid()),

('802.1X Authentication', 'Technical', 'Network Security', 'critical', 'functional',
 'All network access must use 802.1X authentication with certificate-based security',
 'Ensure strong authentication and prevent unauthorized network access',
 '["Certificate-based auth", "EAP-TLS support", "Auto-provisioning", "Revocation checking"]'::jsonb,
 '["security_testing", "certificate_testing", "revocation_testing"]'::jsonb,
 '["EAP-TLS authentication", "Certificate deployment", "Revocation test"]'::jsonb,
 '["PKI Infrastructure", "Certificate templates", "RADIUS server"]'::jsonb,
 '["Certificate lifecycle management", "OCSP/CRL access"]'::jsonb,
 '["PKI is properly configured", "Devices support EAP-TLS"]'::jsonb,
 '["Secure Authentication", "Certificate Management"]'::jsonb,
 '["802.1X Support", "Certificate Deployment", "EAP Methods"]'::jsonb,
 '{"cisco": {"ios_version": "15.2+"}, "aruba": {"clearpass_version": "6.9+"}}'::jsonb,
 '["PCI DSS", "HIPAA", "SOX"]'::jsonb,
 '["802.1x", "certificates", "eap-tls", "pki"]'::jsonb,
 'approved', auth.uid()),

-- Compliance Requirements
('HIPAA Audit Logging', 'Compliance', 'Healthcare', 'critical', 'regulatory',
 'System must provide comprehensive audit logging for HIPAA compliance',
 'Meet healthcare regulatory requirements for access monitoring and audit trails',
 '["All access logged", "Tamper-proof logs", "12-month retention", "Automated reports"]'::jsonb,
 '["audit_review", "compliance_testing", "report_validation"]'::jsonb,
 '["Log integrity test", "Retention test", "Report generation test"]'::jsonb,
 '["Log management system", "Secure storage", "Backup solution"]'::jsonb,
 '["Log storage capacity", "Retention policies"]'::jsonb,
 '["Audit requirements defined", "Storage is secure"]'::jsonb,
 '["Compliance Reporting", "Audit Trail", "Access Monitoring"]'::jsonb,
 '["Audit Logging", "Report Generation", "Data Retention"]'::jsonb,
 '{"splunk": {"version": "8.2+"}, "qradar": {"version": "7.4+"}}'::jsonb,
 '["HIPAA"]'::jsonb,
 '["hipaa", "audit", "compliance", "logging"]'::jsonb,
 'approved', auth.uid()),

('PCI DSS Network Segmentation', 'Compliance', 'Payment Processing', 'critical', 'regulatory',
 'Network must be segmented to isolate cardholder data environment (CDE)',
 'Comply with PCI DSS requirements for network segmentation and access control',
 '["CDE isolation", "Firewall rules", "Access logging", "Regular testing"]'::jsonb,
 '["penetration_testing", "network_testing", "compliance_audit"]'::jsonb,
 '["Segmentation test", "Firewall rule test", "Access control test"]'::jsonb,
 '["Firewall infrastructure", "Network design", "Monitoring tools"]'::jsonb,
 '["Network topology", "Firewall capabilities"]'::jsonb,
 '["CDE is identified", "Firewalls support required features"]'::jsonb,
 '["Network Segmentation", "Access Control", "Compliance Monitoring"]'::jsonb,
 '["VLAN Assignment", "Firewall Integration", "Policy Enforcement"]'::jsonb,
 '{"paloalto": {"panos_version": "10.1+"}, "fortinet": {"fortios_version": "7.0+"}}'::jsonb,
 '["PCI DSS"]'::jsonb,
 '["pci", "segmentation", "firewall", "cde"]'::jsonb,
 'approved', auth.uid()),

-- Operational Requirements
('Device Auto-Discovery', 'Operational', 'Device Management', 'high', 'functional',
 'System must automatically discover and profile network devices',
 'Reduce manual effort and ensure comprehensive device visibility',
 '["95% accuracy", "30-second profiling", "1000+ device types", "Custom profiles"]'::jsonb,
 '["accuracy_testing", "performance_testing", "scalability_testing"]'::jsonb,
 '["Discovery test", "Classification test", "Performance test"]'::jsonb,
 '["Network scanning", "SNMP access", "Database updates"]'::jsonb,
 '["Network access", "SNMP communities", "Performance impact"]'::jsonb,
 '["Devices respond to discovery", "Network allows scanning"]'::jsonb,
 '["Device Discovery", "Network Visibility", "Asset Management"]'::jsonb,
 '["Device Profiling", "Network Scanning", "Inventory Management"]'::jsonb,
 '{"portnox": {"version": "21.1+"}, "ise": {"version": "3.0+"}}'::jsonb,
 '[]'::jsonb,
 '["discovery", "profiling", "automation", "inventory"]'::jsonb,
 'approved', auth.uid()),

('Guest Access Portal', 'Operational', 'User Experience', 'medium', 'functional',
 'Provide self-service guest access with sponsor approval workflow',
 'Enable secure guest access while maintaining security controls',
 '["Self-registration", "Sponsor approval", "Time limits", "Usage tracking"]'::jsonb,
 '["usability_testing", "workflow_testing", "integration_testing"]'::jsonb,
 '["Registration test", "Approval workflow test", "Access limit test"]'::jsonb,
 '["Web portal", "Email system", "Database"]'::jsonb,
 '["Email delivery", "Web accessibility", "Mobile support"]'::jsonb,
 '["Sponsors identified", "Email system works", "Users have devices"]'::jsonb,
 '["Guest Access", "Self-Service", "Sponsor Workflow"]'::jsonb,
 '["Guest Portal", "Workflow Engine", "Time-based Access"]'::jsonb,
 '{"clearpass": {"version": "6.9+"}, "ise": {"version": "3.0+"}}'::jsonb,
 '[]'::jsonb,
 '["guest", "portal", "workflow", "self-service"]'::jsonb,
 'approved', auth.uid());

-- Enhanced use case library
INSERT INTO use_case_library (name, category, description, business_value, technical_requirements, prerequisites, test_scenarios, supported_vendors, complexity, estimated_effort, dependencies, implementation_phases, success_metrics, risk_factors, mitigation_strategies, related_requirements, portnox_features, industry_applications, tags, status, created_by) VALUES

-- Authentication Use Cases
('Zero Trust Network Access', 'Authentication', 
 'Implement comprehensive zero-trust network access with continuous verification and risk-based decisions',
 'Reduces security breach risk by 70%, ensures compliance, and provides granular access control',
 '["Multi-factor authentication", "Device compliance", "Continuous monitoring", "Risk engine", "Policy automation"]'::jsonb,
 '["Identity provider", "Device management", "Certificate infrastructure", "SIEM integration"]'::jsonb,
 '["MFA authentication", "Device compliance check", "Risk-based access", "Policy enforcement"]'::jsonb,
 '["Portnox", "Microsoft", "Okta", "Palo Alto"]'::jsonb,
 'high', '12-16 weeks',
 '["Active Directory", "PKI", "Device Management", "SIEM"]'::jsonb,
 '["Phase 1: Identity integration", "Phase 2: Device compliance", "Phase 3: Risk engine", "Phase 4: Full automation"]'::jsonb,
 '["Authentication success rate >99%", "Mean time to access <30s", "Security incidents <5/month"]'::jsonb,
 '["Complex integration", "User resistance", "Performance impact"]'::jsonb,
 '["Phased rollout", "User training", "Performance monitoring"]'::jsonb,
 '["Active Directory Integration", "802.1X Authentication", "Device Compliance"]'::jsonb,
 '["Risk-based Authentication", "Continuous Monitoring", "Policy Automation"]'::jsonb,
 '["Financial Services", "Healthcare", "Government", "Critical Infrastructure"]'::jsonb,
 '["zero-trust", "mfa", "risk-based", "continuous"]'::jsonb,
 'approved', auth.uid()),

('IoT Device Security', 'IoT Security',
 'Automated secure onboarding, management, and monitoring of IoT devices with micro-segmentation',
 'Enables secure IoT deployment while maintaining network security and compliance',
 '["Device discovery", "Certificate provisioning", "Micro-segmentation", "Behavioral monitoring"]'::jsonb,
 '["PKI infrastructure", "Network segmentation", "Device inventory", "Monitoring platform"]'::jsonb,
 '["Auto-discovery", "Certificate deployment", "Policy enforcement", "Anomaly detection"]'::jsonb,
 '["Portnox", "Cisco ISE", "Aruba ClearPass"]'::jsonb,
 'medium', '8-12 weeks',
 '["PKI", "Network Infrastructure", "Monitoring Tools"]'::jsonb,
 '["Phase 1: Discovery setup", "Phase 2: Certificate deployment", "Phase 3: Segmentation", "Phase 4: Monitoring"]'::jsonb,
 '["Device onboarding time <5min", "Security incidents 0", "Network performance maintained"]'::jsonb,
 '["Device diversity", "Certificate lifecycle", "Network complexity"]'::jsonb,
 '["Device classification", "Automated certificate renewal", "Network documentation"]'::jsonb,
 '["Device Auto-Discovery", "Certificate Management", "Network Segmentation"]'::jsonb,
 '["IoT Profiling", "Certificate Deployment", "Micro-segmentation"]'::jsonb,
 '["Manufacturing", "Healthcare", "Smart Buildings", "Retail"]'::jsonb,
 '["iot", "certificates", "segmentation", "automation"]'::jsonb,
 'approved', auth.uid()),

-- Compliance Use Cases
('HIPAA Compliance Framework', 'Compliance',
 'Comprehensive HIPAA compliance solution with audit logging, access controls, and reporting',
 'Ensures healthcare compliance, reduces audit costs, and minimizes regulatory risk',
 '["Audit logging", "Access controls", "Encryption", "Breach detection", "Automated reporting"]'::jsonb,
 '["SIEM platform", "Encryption infrastructure", "Backup systems", "Staff training"]'::jsonb,
 '["Access logging", "Encryption verification", "Breach detection", "Report generation"]'::jsonb,
 '["Portnox", "Splunk", "Microsoft", "Cisco"]'::jsonb,
 'high', '16-20 weeks',
 '["SIEM", "Encryption", "Backup", "Training Program"]'::jsonb,
 '["Phase 1: Audit setup", "Phase 2: Access controls", "Phase 3: Encryption", "Phase 4: Reporting"]'::jsonb,
 '["100% audit compliance", "Zero security incidents", "Audit time reduced 50%"]'::jsonb,
 '["Regulatory changes", "Staff compliance", "System complexity"]'::jsonb,
 '["Regular updates", "Ongoing training", "Compliance monitoring"]'::jsonb,
 '["HIPAA Audit Logging", "Access Control", "Data Encryption"]'::jsonb,
 '["Comprehensive Auditing", "Role-based Access", "Automated Compliance"]'::jsonb,
 '["Healthcare", "Medical Devices", "Health Insurance"]'::jsonb,
 '["hipaa", "compliance", "healthcare", "audit"]'::jsonb,
 'approved', auth.uid()),

-- Operational Use Cases  
('Bring Your Own Device (BYOD)', 'Operational',
 'Secure BYOD program with device registration, compliance checking, and managed access',
 'Improves employee productivity while maintaining security and reducing device costs',
 '["Device registration", "Compliance checking", "App management", "Data protection"]'::jsonb,
 '["MDM platform", "Certificate infrastructure", "Policy framework", "Help desk"]'::jsonb,
 '["Device enrollment", "Compliance verification", "App deployment", "Data separation"]'::jsonb,
 '["Microsoft Intune", "VMware Workspace ONE", "Portnox"]'::jsonb,
 'medium', '10-14 weeks',
 '["MDM", "Certificates", "Policies", "Support"]'::jsonb,
 '["Phase 1: Policy creation", "Phase 2: MDM setup", "Phase 3: Pilot program", "Phase 4: Full rollout"]'::jsonb,
 '["User satisfaction >85%", "Security incidents <2/month", "Support tickets <10/week"]'::jsonb,
 '["User resistance", "Device diversity", "Support complexity"]'::jsonb,
 '["User training", "Device standardization", "Self-service portal"]'::jsonb,
 '["Device Management", "Certificate Deployment", "Access Control"]'::jsonb,
 '["BYOD Support", "Device Compliance", "Automated Enrollment"]'::jsonb,
 '["Professional Services", "Education", "Remote Work"]'::jsonb,
 '["byod", "mdm", "mobile", "productivity"]'::jsonb,
 'approved', auth.uid());

-- Enhanced project templates  
INSERT INTO project_templates (name, description, industry, deployment_type, security_level, compliance_frameworks, requirements, use_cases, test_cases, authentication_workflows, vendor_configurations, network_requirements, timeline_template, created_by) VALUES

('Healthcare HIPAA Deployment', 
 'Complete NAC deployment for healthcare organizations with HIPAA compliance requirements',
 'Healthcare', 'On-Premises with Cloud Management', 'High Security',
 '["HIPAA", "HITECH"]'::text[],
 '["HIPAA Audit Logging", "802.1X Authentication", "Device Auto-Discovery"]'::jsonb,
 '["HIPAA Compliance Framework", "IoT Device Security", "Zero Trust Network Access"]'::jsonb,
 '["Authentication testing", "Compliance verification", "Audit logging test"]'::jsonb,
 '["EAP-TLS Certificate Authentication", "Device Profiling", "Guest Access"]'::jsonb,
 '["Cisco ISE Primary", "Aruba Wireless", "Palo Alto Firewall"]'::jsonb,
 '["Segmented VLANs", "Encrypted connections", "Redundant infrastructure"]'::jsonb,
 '{"total_duration": "20-24 weeks", "phases": [{"name": "Planning", "duration": "4 weeks"}, {"name": "Implementation", "duration": "12 weeks"}, {"name": "Testing", "duration": "4 weeks"}, {"name": "Deployment", "duration": "4 weeks"}]}'::jsonb,
 auth.uid()),

('Financial Services Zero Trust',
 'Zero trust network access implementation for financial institutions with regulatory compliance',
 'Financial Services', 'Hybrid Cloud', 'Maximum Security',
 '["PCI DSS", "SOX", "GLBA"]'::text[],
 '["Zero Trust Authentication", "PCI DSS Segmentation", "Privileged Access Management"]'::jsonb,
 '["Zero Trust Network Access", "Privileged User Access", "Transaction Security"]'::jsonb,
 '["Zero trust verification", "Segmentation testing", "Privileged access test"]'::jsonb,
 '["Multi-factor Authentication", "Risk-based Access", "Continuous Monitoring"]'::jsonb,
 '["Portnox Primary", "Palo Alto NGFW", "Okta Identity", "Splunk SIEM"]'::jsonb,
 '["Zero trust architecture", "Micro-segmentation", "Encrypted everything"]'::jsonb,
 '{"total_duration": "24-28 weeks", "phases": [{"name": "Assessment", "duration": "6 weeks"}, {"name": "Design", "duration": "6 weeks"}, {"name": "Implementation", "duration": "12 weeks"}, {"name": "Validation", "duration": "4 weeks"}]}'::jsonb,
 auth.uid()),

('Manufacturing IoT Security',
 'Industrial IoT security deployment with operational technology (OT) network protection',
 'Manufacturing', 'On-Premises', 'High Security',
 '["IEC 62443", "NIST Cybersecurity Framework"]'::text[],
 '["OT Network Security", "IoT Device Management", "Industrial Protocol Support"]'::jsonb,
 '["IoT Device Security", "OT Network Monitoring", "Supply Chain Security"]'::jsonb,
 '["OT/IT segmentation test", "Device authentication test", "Protocol security test"]'::jsonb,
 '["Industrial Device Authentication", "OT Protocol Inspection", "Asset Discovery"]'::jsonb,
 '["Cisco Industrial", "Fortinet OT Security", "Portnox Edge"]'::jsonb,
 '["OT/IT segmentation", "Industrial protocols", "Ruggedized hardware"]'::jsonb,
 '{"total_duration": "16-20 weeks", "phases": [{"name": "OT Assessment", "duration": "4 weeks"}, {"name": "Segmentation", "duration": "6 weeks"}, {"name": "Device Security", "duration": "6 weeks"}, {"name": "Monitoring", "duration": "4 weeks"}]}'::jsonb,
 auth.uid()),

('Education Campus Network',
 'Comprehensive campus network security for educational institutions with student device support',
 'Education', 'Hybrid', 'Medium Security',
 '["FERPA", "CIPA"]'::text[],
 '["Student Device Support", "Guest Access", "Content Filtering"]'::jsonb,
 '["Bring Your Own Device (BYOD)", "Guest Access Management", "Content Security"]'::jsonb,
 '["Student enrollment test", "Guest access test", "Content filtering test"]'::jsonb,
 '["Self-Service Enrollment", "Sponsored Guest Access", "Automatic Provisioning"]'::jsonb,
 '["Aruba Campus", "Cisco Meraki", "Content Filter"]'::jsonb,
 '["Campus-wide WiFi", "Residence hall networks", "Guest isolation"]'::jsonb,
 '{"total_duration": "12-16 weeks", "phases": [{"name": "Infrastructure", "duration": "4 weeks"}, {"name": "Wireless Deployment", "duration": "6 weeks"}, {"name": "User Onboarding", "duration": "4 weeks"}, {"name": "Policy Refinement", "duration": "2 weeks"}]}'::jsonb,
 auth.uid()),

('Retail PCI Compliance',
 'Point-of-sale security and PCI DSS compliance for retail organizations',
 'Retail', 'Hybrid Cloud', 'High Security',
 '["PCI DSS"]'::text[],
 '["POS Security", "PCI Network Segmentation", "Payment Processing Security"]'::jsonb,
 '["PCI DSS Network Segmentation", "POS Device Security", "Customer Data Protection"]'::jsonb,
 '["PCI segmentation test", "POS security test", "Cardholder data test"]'::jsonb,
 '["POS Device Authentication", "Customer Network Isolation", "Payment Security"]'::jsonb,
 '["Cisco ISE", "Palo Alto NGFW", "Retail Switches"]'::jsonb,
 '["PCI compliant segmentation", "POS network isolation", "Customer WiFi separation"]'::jsonb,
 '{"total_duration": "14-18 weeks", "phases": [{"name": "PCI Assessment", "duration": "3 weeks"}, {"name": "Network Redesign", "duration": "5 weeks"}, {"name": "Security Implementation", "duration": "6 weeks"}, {"name": "PCI Validation", "duration": "4 weeks"}]}'::jsonb,
 auth.uid());