-- Add comprehensive vendor library with correct constraint values
INSERT INTO vendor_library (vendor_name, vendor_type, category, description, website_url, support_contact, models, supported_protocols, integration_methods, portnox_compatibility, configuration_templates, known_limitations, firmware_requirements, documentation_links, support_level, portnox_integration_level, portnox_documentation, certifications, status) VALUES

-- Wired Infrastructure Vendors (using 'full' instead of 'enterprise')
('HPE Aruba Switching', 'network_infrastructure', 'wired', 'Enterprise switching solutions with ClearPass integration', 'https://www.arubanetworks.com', '{"email": "support@arubanetworks.com", "phone": "+1-408-227-4500"}', '["6200F", "6300F", "6300M", "6400", "8325", "8360", "8400"]', '["802.1X", "MAB", "LLDP", "SNMP", "RADIUS"]', '["RADIUS", "ClearPass", "Central"]', '{"level": "excellent", "certified": true, "testing_status": "validated"}', '["campus_switch", "l3_routing", "security_basic"]', '["firmware_compatibility"]', '["ArubaOS-CX 10.08+"]', '{"datasheet": "arubanetworks.com/products/switches/", "config_guide": "arubanetworks.com/support/"}', 'full', 'certified', '{"integration_guide": "portnox.com/integrations/aruba", "config_examples": "yes"}', '["Portnox Certified", "ISO 9001"]', 'active'),

('Cisco Catalyst', 'network_infrastructure', 'wired', 'Industry-leading enterprise switching portfolio', 'https://www.cisco.com', '{"email": "support@cisco.com", "phone": "+1-800-553-2447"}', '["9200", "9300", "9400", "9500", "9600", "3850", "2960X"]', '["802.1X", "MAB", "NEAT", "RADIUS", "TACACS+"]', '["RADIUS", "ISE", "DNAC"]', '{"level": "excellent", "certified": true, "testing_status": "validated"}', '["basic_l2", "l3_routing", "security", "datacenter"]', '["licensing_complexity"]', '["IOS-XE 16.12+", "IOS 15.2+"]', '{"datasheet": "cisco.com/c/en/us/products/switches/", "config_guide": "cisco.com/c/en/us/support/"}', 'full', 'certified', '{"integration_guide": "portnox.com/integrations/cisco", "config_examples": "yes"}', '["Portnox Certified", "Common Criteria"]', 'active'),

('Juniper EX Series', 'network_infrastructure', 'wired', 'High-performance Ethernet switches', 'https://www.juniper.net', '{"email": "support@juniper.net", "phone": "+1-888-314-5822"}', '["EX2300", "EX3400", "EX4300", "EX4400", "EX4600", "EX4650"]', '["802.1X", "RADIUS", "TACACS+", "SNMP"]', '["RADIUS", "Junos Space"]', '{"level": "good", "certified": false, "testing_status": "compatible"}', '["basic_l2", "l3_routing", "security"]', '["junos_syntax"]', '["Junos 18.4+"]', '{"datasheet": "juniper.net/us/en/products/switches/", "config_guide": "juniper.net/documentation/"}', 'partial', 'compatible', '{"integration_guide": "portnox.com/integrations/juniper", "config_examples": "basic"}', '["FIPS 140-2"]', 'active'),

('Extreme Networks', 'network_infrastructure', 'wired', 'Cloud-driven networking solutions', 'https://www.extremenetworks.com', '{"email": "support@extremenetworks.com", "phone": "+1-408-579-2800"}', '["X435", "X440", "X450", "X465", "X590", "X620", "X690"]', '["802.1X", "RADIUS", "LLDP", "SNMP"]', '["RADIUS", "ExtremeCloud"]', '{"level": "good", "certified": true, "testing_status": "validated"}', '["campus_switch", "fabric_attach"]', '["cloud_dependency"]', '["EXOS 31.x+"]', '{"datasheet": "extremenetworks.com/products/switches/", "config_guide": "extremenetworks.com/support/"}', 'full', 'certified', '{"integration_guide": "portnox.com/integrations/extreme", "config_examples": "yes"}', '["Portnox Certified"]', 'active'),

-- Wireless Infrastructure Vendors  
('Cisco Wireless', 'wireless_infrastructure', 'wireless', 'Enterprise wireless controllers and APs', 'https://www.cisco.com', '{"email": "support@cisco.com", "phone": "+1-800-553-2447"}', '["9800-CL", "9800-L", "9800-40", "9800-80", "9130AXI", "9136I", "9166I"]', '["802.1X", "PSK", "RADIUS", "WPA3", "OWE"]', '["RADIUS", "ISE", "DNAC", "CAPWAP"]', '{"level": "excellent", "certified": true, "testing_status": "validated"}', '["enterprise", "guest", "byod", "iot"]', '["dna_licensing"]', '["IOS-XE 17.3+"]', '{"datasheet": "cisco.com/c/en/us/products/wireless/", "config_guide": "cisco.com/c/en/us/support/wireless/"}', 'full', 'certified', '{"integration_guide": "portnox.com/integrations/cisco-wireless", "config_examples": "yes"}', '["Portnox Certified", "WiFi Alliance"]', 'active'),

('HPE Aruba Wireless', 'wireless_infrastructure', 'wireless', 'Cloud-native wireless management', 'https://www.arubanetworks.com', '{"email": "support@arubanetworks.com", "phone": "+1-408-227-4500"}', '["515", "535", "555", "575", "635", "7030", "7205", "7220"]', '["802.1X", "PSK", "RADIUS", "WPA3", "Enhanced Open"]', '["RADIUS", "ClearPass", "Central Cloud"]', '{"level": "excellent", "certified": true, "testing_status": "validated"}', '["campus", "branch", "guest", "iot"]', '["cloud_dependency"]', '["ArubaOS 8.8+", "Instant 8.10+"]', '{"datasheet": "arubanetworks.com/products/wireless/", "config_guide": "arubanetworks.com/support/"}', 'full', 'certified', '{"integration_guide": "portnox.com/integrations/aruba-wireless", "config_examples": "yes"}', '["Portnox Certified", "WiFi Alliance"]', 'active'),

('Ruckus Networks', 'wireless_infrastructure', 'wireless', 'High-performance wireless solutions', 'https://www.commscope.com/ruckus', '{"email": "support@commscope.com", "phone": "+1-800-CommScope"}', '["R350", "R550", "R650", "R750", "R850", "SmartZone"]', '["802.1X", "PSK", "RADIUS", "WPA3"]', '["RADIUS", "SmartZone", "Cloud"]', '{"level": "good", "certified": true, "testing_status": "validated"}', '["beamflex", "channelfly", "wifi6"]', '["management_complexity"]', '["SmartZone 6.0+"]', '{"datasheet": "commscope.com/ruckus/", "config_guide": "support.ruckuswireless.com/"}', 'full', 'certified', '{"integration_guide": "portnox.com/integrations/ruckus", "config_examples": "yes"}', '["Portnox Certified"]', 'active'),

-- NAC/RADIUS Providers (Competitive Analysis)
('Cisco ISE', 'nac_radius', 'nac', 'Identity Services Engine', 'https://www.cisco.com/c/en/us/products/security/identity-services-engine/', '{"email": "support@cisco.com", "phone": "+1-800-553-2447"}', '["ISE 2.7", "ISE 3.0", "ISE 3.1", "ISE 3.2", "ISE 3.3"]', '["RADIUS", "TACACS+", "EAP-TLS", "PEAP", "EAP-FAST"]', '["API", "pxGrid", "Active Directory"]', '{"level": "competitive", "certified": false, "testing_status": "alternative"}', '["policy_enforcement", "guest_access", "byod"]', '["complexity", "licensing_cost", "vendor_lock_in"]', '["ISE 3.0+"]', '{"datasheet": "cisco.com/c/en/us/products/security/identity-services-engine/", "config_guide": "cisco.com/c/en/us/support/security/"}', 'none', 'competitive', '{"comparison_guide": "portnox.com/vs/cisco-ise", "migration_guide": "yes"}', '["Common Criteria"]', 'active'),

('Aruba ClearPass', 'nac_radius', 'nac', 'Network access control platform', 'https://www.arubanetworks.com/products/security/network-access-control/', '{"email": "support@arubanetworks.com", "phone": "+1-408-227-4500"}', '["ClearPass 6.9", "ClearPass 6.10", "ClearPass 6.11", "ClearPass 6.12"]', '["RADIUS", "TACACS+", "EAP-TLS", "PEAP", "EAP-TTLS"]', '["API", "Active Directory", "LDAP"]', '{"level": "competitive", "certified": false, "testing_status": "alternative"}', '["policy_manager", "guest", "onboard"]', '["aruba_dependency", "licensing_complexity"]', '["ClearPass 6.9+"]', '{"datasheet": "arubanetworks.com/products/security/network-access-control/", "config_guide": "arubanetworks.com/support/"}', 'none', 'competitive', '{"comparison_guide": "portnox.com/vs/clearpass", "migration_guide": "yes"}', '["Common Criteria"]', 'active'),

('Microsoft NPS', 'nac_radius', 'radius', 'Windows Network Policy Server', 'https://docs.microsoft.com/en-us/windows-server/networking/technologies/nps/', '{"email": "support@microsoft.com"}', '["Windows Server 2016", "Windows Server 2019", "Windows Server 2022"]', '["RADIUS", "EAP-TLS", "PEAP", "EAP-TTLS"]', '["Active Directory", "Group Policy"]', '{"level": "basic", "certified": false, "testing_status": "compatible"}', '["basic_radius", "ad_integration"]', '["limited_features", "windows_only"]', '["Windows Server 2016+"]', '{"datasheet": "docs.microsoft.com/en-us/windows-server/networking/technologies/nps/", "config_guide": "docs.microsoft.com/en-us/windows-server/"}', 'partial', 'compatible', '{"integration_guide": "portnox.com/integrations/nps", "config_examples": "basic"}', '["Microsoft Certified"]', 'active'),

-- Security Vendors (Integration Partners)
('Palo Alto Networks', 'security', 'firewall', 'Next-generation firewalls and security', 'https://www.paloaltonetworks.com', '{"email": "support@paloaltonetworks.com", "phone": "+1-866-898-9087"}', '["PA-220", "PA-850", "PA-3220", "PA-5220", "VM-Series", "Prisma"]', '["RADIUS", "SAML", "LDAP", "Kerberos"]', '["API", "User-ID", "GlobalProtect"]', '{"level": "good", "certified": false, "testing_status": "compatible"}', '["user_id_integration", "globalprotect"]', '["user_mapping_complexity"]', '["PAN-OS 10.0+"]', '{"datasheet": "paloaltonetworks.com/products/", "config_guide": "docs.paloaltonetworks.com/"}', 'partial', 'compatible', '{"integration_guide": "portnox.com/integrations/palo-alto", "config_examples": "basic"}', '["Common Criteria"]', 'active'),

('Fortinet', 'security', 'firewall', 'Secure networking and security', 'https://www.fortinet.com', '{"email": "support@fortinet.com", "phone": "+1-866-648-4638"}', '["FortiGate 60F", "FortiGate 100F", "FortiGate 200F", "FortiAP", "FortiSwitch"]', '["RADIUS", "LDAP", "SAML"]', '["FortiOS API", "Fabric Connector"]', '{"level": "good", "certified": true, "testing_status": "validated"}', '["fortigate_integration", "fortinet_fabric"]', '["proprietary_protocols"]', '["FortiOS 7.0+"]', '{"datasheet": "fortinet.com/products/", "config_guide": "docs.fortinet.com/"}', 'full', 'certified', '{"integration_guide": "portnox.com/integrations/fortinet", "config_examples": "yes"}', '["Portnox Certified"]', 'active');