-- Add comprehensive authentication methods
INSERT INTO authentication_methods (name, method_type, description, security_level, configuration_complexity, portnox_integration, vendor_support, documentation_links) VALUES
('802.1X', 'network', 'IEEE 802.1X port-based network access control', 'high', 'high', '{"native": true, "configuration_complexity": "high", "recommended_scenarios": ["enterprise", "secure_networks"]}', '["cisco", "aruba", "juniper", "extreme"]', '["https://docs.portnox.com/802.1x"]'),
('Active Directory', 'directory', 'Microsoft Active Directory domain authentication', 'high', 'medium', '{"native": true, "ldap_integration": true, "kerberos_support": true}', '["microsoft", "portnox"]', '["https://docs.portnox.com/active-directory"]'),
('LDAP', 'directory', 'Lightweight Directory Access Protocol', 'medium', 'medium', '{"native": true, "secure_ldap": true, "bind_authentication": true}', '["openldap", "389ds", "oracle"]', '["https://docs.portnox.com/ldap"]'),
('RADIUS', 'network', 'Remote Authentication Dial-In User Service', 'high', 'medium', '{"native": true, "accounting": true, "dynamic_authorization": true}', '["freeradius", "cisco", "aruba"]', '["https://docs.portnox.com/radius"]'),
('SAML SSO', 'federation', 'Security Assertion Markup Language Single Sign-On', 'high', 'high', '{"native": true, "sp_initiated": true, "idp_initiated": true}', '["azure_ad", "okta", "adfs"]', '["https://docs.portnox.com/saml"]'),
('TACACS+', 'network', 'Terminal Access Controller Access-Control System Plus', 'high', 'medium', '{"native": true, "accounting": true, "authorization": true}', '["cisco", "juniper", "aruba"]', '["https://docs.portnox.com/tacacs"]'),
('OAuth 2.0', 'federation', 'Open Authorization 2.0 framework', 'medium', 'medium', '{"native": true, "bearer_tokens": true, "refresh_tokens": true}', '["google", "microsoft", "auth0"]', '["https://docs.portnox.com/oauth"]'),
('OpenID Connect', 'federation', 'Identity layer on top of OAuth 2.0', 'high', 'medium', '{"native": true, "id_tokens": true, "userinfo_endpoint": true}', '["azure_ad", "okta", "auth0"]', '["https://docs.portnox.com/oidc"]'),
('Kerberos', 'network', 'Network authentication protocol', 'high', 'high', '{"native": true, "ticket_granting": true, "mutual_authentication": true}', '["microsoft", "mit", "heimdal"]', '["https://docs.portnox.com/kerberos"]'),
('Certificate-based', 'certificate', 'X.509 digital certificate authentication', 'very_high', 'high', '{"native": true, "client_certificates": true, "ca_validation": true}', '["microsoft_ca", "openssl", "sectigo"]', '["https://docs.portnox.com/certificates"]'),
('Multi-Factor Authentication', 'mfa', 'Multiple authentication factors', 'very_high', 'medium', '{"native": true, "totp": true, "sms": false, "push": true}', '["duo", "okta", "azure_mfa"]', '["https://docs.portnox.com/mfa"]'),
('Local Database', 'local', 'Local user database authentication', 'low', 'low', '{"native": true, "password_policy": true, "user_management": true}', '["portnox"]', '["https://docs.portnox.com/local-auth"]'),
('Guest Portal', 'portal', 'Web-based guest authentication', 'medium', 'low', '{"native": true, "customizable": true, "self_registration": true}', '["portnox"]', '["https://docs.portnox.com/guest-portal"]'),
('MAC Authentication Bypass', 'network', 'Device MAC address authentication', 'low', 'low', '{"native": true, "device_profiling": true, "auto_registration": true}', '["cisco", "aruba", "extreme"]', '["https://docs.portnox.com/mab"]'),
('Web Authentication', 'portal', 'HTTP/HTTPS web-based authentication', 'medium', 'low', '{"native": true, "captive_portal": true, "redirect_support": true}', '["cisco", "aruba", "fortinet"]', '["https://docs.portnox.com/web-auth"]');

-- Create device types library
CREATE TABLE IF NOT EXISTS public.device_types_library (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  name text NOT NULL,
  category text NOT NULL,
  subcategory text,
  description text,
  typical_os_versions jsonb DEFAULT '[]'::jsonb,
  network_requirements jsonb DEFAULT '{}'::jsonb,
  security_considerations jsonb DEFAULT '[]'::jsonb,
  authentication_methods jsonb DEFAULT '[]'::jsonb,
  deployment_considerations jsonb DEFAULT '[]'::jsonb,
  monitoring_requirements jsonb DEFAULT '[]'::jsonb,
  compliance_requirements jsonb DEFAULT '[]'::jsonb,
  vendor_specific_notes jsonb DEFAULT '{}'::jsonb,
  risk_level text DEFAULT 'medium',
  management_complexity text DEFAULT 'medium',
  is_active boolean DEFAULT true,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now()
);

-- Enable RLS on device_types_library
ALTER TABLE public.device_types_library ENABLE ROW LEVEL SECURITY;

-- Create RLS policies for device_types_library
CREATE POLICY "Resource library readable by authenticated users" ON public.device_types_library
  FOR SELECT USING (true);

CREATE POLICY "Users can create device types" ON public.device_types_library
  FOR INSERT WITH CHECK (true);

CREATE POLICY "Users can update device types" ON public.device_types_library
  FOR UPDATE USING (true);

-- Add trigger for updated_at
CREATE TRIGGER update_device_types_library_updated_at
  BEFORE UPDATE ON public.device_types_library
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();

-- Insert comprehensive device types
INSERT INTO device_types_library (name, category, subcategory, description, typical_os_versions, network_requirements, security_considerations, authentication_methods, deployment_considerations, monitoring_requirements, compliance_requirements, vendor_specific_notes, risk_level, management_complexity) VALUES
-- Corporate Endpoints
('Corporate Laptops', 'endpoints', 'corporate', 'Business laptops and notebooks', '["Windows 10/11", "macOS 12+", "Ubuntu 20.04+"]', '{"wired": "required", "wireless": "required", "vpn": "required"}', '["endpoint_protection", "encryption", "secure_boot"]', '["802.1x", "certificate", "active_directory"]', '["imaging", "domain_join", "policy_deployment"]', '["asset_tracking", "compliance_monitoring", "performance"]', '["hipaa", "pci_dss", "sox"]', '{"dell": "business_class", "hp": "elitebook_series", "lenovo": "thinkpad_series"}', 'medium', 'medium'),
('Desktop Workstations', 'endpoints', 'corporate', 'Fixed desktop computers', '["Windows 10/11", "macOS", "Linux"]', '{"wired": "required", "wireless": "optional"}', '["endpoint_protection", "encryption", "physical_security"]', '["802.1x", "certificate", "active_directory"]', '["imaging", "domain_join", "kiosk_mode"]', '["asset_tracking", "compliance_monitoring"]', '["hipaa", "pci_dss"]', '{"dell": "optiplex", "hp": "prodesk", "lenovo": "thinkcentre"}', 'low', 'low'),
('Executive Devices', 'endpoints', 'corporate', 'High-priority executive devices', '["Windows 11", "macOS latest", "iOS latest"]', '{"wired": "required", "wireless": "required", "5g": "optional"}', '["advanced_threat_protection", "dlp", "encryption"]', '["certificate", "mfa", "biometric"]', '["white_glove_setup", "priority_support"]', '["enhanced_monitoring", "executive_dashboards"]', '["all_frameworks"]', '{"apple": "business_premium", "dell": "latitude_premium"}', 'high', 'high'),

-- Mobile Devices
('Smartphones', 'mobile', 'phone', 'Corporate and BYOD smartphones', '["iOS 15+", "Android 11+"]', '{"wireless": "required", "cellular": "required"}', '["mdm_enrollment", "app_wrapping", "containerization"]', '["certificate", "pin", "biometric"]', '["mdm_deployment", "app_catalog", "byod_policy"]', '["location_tracking", "app_usage", "security_posture"]', '["privacy_regulations", "data_residency"]', '{"apple": "dep_enrollment", "samsung": "knox_platform", "google": "android_enterprise"}', 'high', 'high'),
('Tablets', 'mobile', 'tablet', 'Business tablets and iPads', '["iOS 15+", "Android 11+", "Windows 11"]', '{"wireless": "required", "cellular": "optional"}', '["mdm_enrollment", "app_management", "content_filtering"]', '["certificate", "pin", "face_recognition"]', '["kiosk_mode", "shared_device", "user_assignment"]', '["usage_analytics", "compliance_reporting"]', '["privacy_regulations"]', '{"apple": "shared_ipad", "samsung": "knox_configure", "microsoft": "surface_management"}', 'medium', 'medium'),
('Wearable Devices', 'mobile', 'wearable', 'Smartwatches and fitness trackers', '["watchOS", "Wear OS", "Tizen"]', '{"bluetooth": "required", "wifi": "optional"}', '["data_encryption", "health_data_protection"]', '["pin", "biometric", "proximity"]', '["companion_app", "health_compliance"]', '["health_metrics", "location_data"]', '["hipaa", "gdpr"]', '{"apple": "apple_watch", "samsung": "galaxy_watch", "fitbit": "enterprise"}', 'medium', 'low'),

-- IoT Devices
('Smart Sensors', 'iot', 'sensors', 'Environmental and monitoring sensors', '["Custom embedded", "Linux IoT", "RTOS"]', '{"wireless": "required", "low_power": "required"}', '["device_identity", "encrypted_communication", "secure_provisioning"]', '["certificate", "psk", "device_id"]', '["bulk_provisioning", "ota_updates", "lifecycle_management"]', '["telemetry_collection", "anomaly_detection"]', '["iot_security_frameworks"]', '{"bosch": "sensortec", "honeywell": "industrial", "siemens": "building_automation"}', 'medium', 'low'),
('Smart Building Controls', 'iot', 'building', 'HVAC, lighting, and building automation', '["BACnet", "Modbus", "Custom firmware"]', '{"ethernet": "preferred", "wireless": "backup"}', '["network_segmentation", "firmware_integrity"]', '["certificate", "shared_key", "device_authentication"]', '["commissioning", "integration_testing", "redundancy"]', '["energy_monitoring", "fault_detection"]', '["building_codes", "energy_regulations"]', '{"johnson_controls": "metasys", "schneider": "ecostruxure", "siemens": "desigo"}', 'low', 'medium'),
('Industrial IoT', 'iot', 'industrial', 'Manufacturing and process control devices', '["Industrial Linux", "VxWorks", "QNX"]', '{"ethernet": "required", "fieldbus": "required"}', '["safety_systems", "operational_technology_security"]', '["certificate", "mutual_authentication"]', '["safety_certification", "hazardous_area_compliance"]', '["operational_metrics", "safety_monitoring"]', '["iec_62443", "nist_cybersecurity"]', '{"rockwell": "factorytalk", "siemens": "simatic", "ge": "predix"}', 'high', 'high'),

-- Printers and MFPs
('Network Printers', 'peripherals', 'printer', 'Standard office printers', '["Printer firmware", "Embedded Linux"]', '{"ethernet": "required", "wireless": "optional"}', '["print_encryption", "user_authentication", "audit_logging"]', '["active_directory", "card_reader", "pin"]', '["driver_deployment", "print_queue_setup"]', '["print_volume", "supply_levels", "error_tracking"]', '["document_security", "privacy_regulations"]', '{"hp": "jetdirect", "canon": "imagerunner", "xerox": "connectkey"}', 'medium', 'low'),
('Multifunction Printers', 'peripherals', 'mfp', 'All-in-one printer/scanner/fax devices', '["Embedded OS", "Android-based"]', '{"ethernet": "required", "wireless": "optional"}', '["document_encryption", "secure_erase", "access_control"]', '["active_directory", "card_reader", "biometric"]', '["feature_activation", "workflow_setup", "integration"]', '["usage_analytics", "document_tracking", "compliance_reports"]', '["document_retention", "privacy_laws"]', '{"ricoh": "smartoperation", "konica_minolta": "bizhub", "sharp": "sharpdesk"}', 'medium', 'medium'),
('Label Printers', 'peripherals', 'specialized', 'Specialized label and barcode printers', '["Printer firmware", "ZPL", "EPL"]', '{"ethernet": "required", "usb": "optional"}', '["print_authentication", "label_verification"]', '["local_authentication", "network_authentication"]', '["driver_setup", "label_design", "integration"]', '["print_volume", "ribbon_levels"]', '["industry_specific"]', '{"zebra": "link_os", "brady": "workstation", "dymo": "labelwriter"}', 'low', 'low'),

-- Security Cameras
('IP Cameras', 'security', 'surveillance', 'Network-connected security cameras', '["Embedded Linux", "Custom firmware"]', '{"ethernet": "preferred", "wifi": "optional", "poe": "preferred"}', '["video_encryption", "secure_streaming", "firmware_integrity"]', '["certificate", "digest_authentication", "onvif"]', '["mounting", "network_configuration", "recording_setup"]', '["video_analytics", "motion_detection", "storage_monitoring"]', '["privacy_regulations", "surveillance_laws"]', '{"axis": "vapix", "hikvision": "sadp", "dahua": "smartpss"}', 'medium', 'medium'),
('NVR Systems', 'security', 'recording', 'Network Video Recorder systems', '["Embedded Linux", "Windows IoT"]', '{"ethernet": "required", "high_bandwidth": "required"}', '["storage_encryption", "user_access_control", "backup_security"]', '["active_directory", "local_accounts", "certificate"]', '["storage_planning", "redundancy_setup", "integration"]', '["storage_health", "recording_status", "system_performance"]', '["data_retention", "privacy_compliance"]', '{"milestone": "xprotect", "genetec": "security_center", "avigilon": "control_center"}', 'medium', 'medium'),
('Access Control Panels', 'security', 'access', 'Door and gate access control systems', '["Embedded firmware", "Real-time OS"]', '{"ethernet": "required", "rs485": "backup"}', '["anti_passback", "encryption", "tamper_detection"]', '["card_reader", "biometric", "pin"]', '["door_hardware", "integration_testing", "backup_power"]', '["access_logs", "door_status", "alarm_monitoring"]', '["physical_security_standards"]', '{"hid": "vertx", "tyco": "exacq", "honeywell": "pro_watch"}', 'high', 'high'),

-- VoIP Phones
('Desk Phones', 'communications', 'telephony', 'Traditional desk-based VoIP phones', '["SIP firmware", "Proprietary OS"]', '{"ethernet": "required", "poe": "preferred"}', '["sip_encryption", "secure_provisioning", "call_encryption"]', '["sip_authentication", "certificate", "digest"]', '["auto_provisioning", "pbx_integration", "feature_programming"]', '["call_quality", "registration_status", "feature_usage"]', '["telecommunications_regulations"]', '{"cisco": "unified_ip", "polycom": "soundpoint", "yealink": "sip_t"}', 'low', 'low'),
('Conference Phones', 'communications', 'conference', 'Room-based conference systems', '["Conference firmware", "Android-based"]', '{"ethernet": "required", "wifi": "optional", "high_bandwidth": "preferred"}', '["meeting_encryption", "participant_authentication"]', '["meeting_pin", "calendar_integration", "sso"]', '["room_setup", "audio_calibration", "integration_testing"]', '["meeting_analytics", "room_utilization", "audio_quality"]', '["meeting_privacy", "recording_compliance"]', '{"polycom": "realpresence", "cisco": "webex_room", "zoom": "zoom_rooms"}', 'medium', 'medium'),
('Softphones', 'communications', 'software', 'Software-based phone applications', '["Windows", "macOS", "iOS", "Android"]', '{"ethernet_or_wifi": "required", "qos": "recommended"}', '["app_security", "credential_protection", "call_encryption"]', '["sso", "username_password", "certificate"]', '["msi_deployment", "user_training", "policy_configuration"]', '["call_analytics", "user_adoption", "performance_metrics"]', '["privacy_regulations", "recording_consent"]', '{"cisco": "jabber", "microsoft": "teams", "zoom": "zoom_phone"}', 'medium', 'low'),

-- Medical Devices
('Patient Monitors', 'medical', 'monitoring', 'Bedside patient monitoring equipment', '["Medical grade firmware", "Real-time OS"]', '{"ethernet": "required", "wireless": "backup", "medical_grade": "required"}', '["patient_data_encryption", "hipaa_compliance", "device_authentication"]', '["certificate", "device_id", "secure_pairing"]', '["clinical_validation", "integration_testing", "staff_training"]', '["patient_data", "device_status", "alarm_management"]', '["hipaa", "fda_regulations", "iec_62304"]', '{"philips": "intellivue", "ge": "carescape", "mindray": "umic"}', 'very_high', 'high'),
('Infusion Pumps', 'medical', 'therapeutic', 'IV medication delivery systems', '["Medical firmware", "Safety-critical OS"]', '{"ethernet": "optional", "wireless": "optional", "isolated_network": "preferred"}', '["medication_safety", "tamper_resistance", "audit_logging"]', '["device_authentication", "nurse_verification"]', '["clinical_protocols", "drug_library_setup", "safety_testing"]', '["infusion_data", "alarm_history", "maintenance_status"]', '["fda_regulations", "joint_commission", "ismp_guidelines"]', '{"bd": "alaris", "baxter": "sigma", "hospira": "plum"}', 'very_high', 'very_high'),
('Imaging Equipment', 'medical', 'diagnostic', 'X-ray, CT, MRI, and ultrasound systems', '["Medical imaging OS", "DICOM compliant"]', '{"ethernet": "required", "high_bandwidth": "required", "isolated_network": "preferred"}', '["image_encryption", "patient_privacy", "access_control"]', '["technologist_login", "physician_access", "certificate"]', '["calibration", "safety_testing", "pacs_integration"]', '["image_quality", "study_metrics", "equipment_status"]', '["hipaa", "dicom", "iec_standards"]', '{"ge": "centricity", "siemens": "syngo", "philips": "intellispace"}', 'very_high', 'very_high'),

-- Industrial Controls
('PLCs', 'industrial', 'control', 'Programmable Logic Controllers', '["Ladder logic", "Function block", "Structured text"]', '{"ethernet": "required", "fieldbus": "required", "redundant": "recommended"}', '["safety_functions", "secure_communication", "change_control"]', '["certificate", "role_based_access", "engineering_authentication"]', '["safety_validation", "commissioning", "operator_training"]', '["process_data", "safety_status", "performance_metrics"]', '["iec_61508", "iec_62443", "nist_cybersecurity"]', '{"allen_bradley": "controllogix", "siemens": "s7", "schneider": "modicon"}', 'high', 'very_high'),
('HMI Terminals', 'industrial', 'interface', 'Human Machine Interface terminals', '["Windows IoT", "Linux embedded", "Proprietary OS"]', '{"ethernet": "required", "redundant": "recommended"}', '["operator_authentication", "screen_security", "audit_logging"]', '["operator_login", "role_based", "card_reader"]', '["graphics_development", "alarm_configuration", "integration_testing"]', '["operator_actions", "alarm_history", "system_performance"]', '["safety_standards", "operational_security"]', '{"wonderware": "intouch", "ge": "proficy", "rockwell": "factorytalk"}', 'medium', 'high'),
('Safety Controllers', 'industrial', 'safety', 'Safety-rated control systems', '["Safety function blocks", "Certified firmware"]', '{"ethernet": "required", "safety_network": "required"}', '["safety_integrity", "secure_boot", "change_validation"]', '["safety_engineer_auth", "dual_approval", "certificate"]', '["safety_validation", "sil_verification", "functional_testing"]', '["safety_metrics", "diagnostic_coverage", "fault_history"]', '["iec_61508", "iec_61511", "machinery_directive"]', '{"pilz": "pnoz", "sick": "flexi", "phoenix": "safetybridg"}', 'very_high', 'very_high'),

-- POS Systems
('Retail Terminals', 'pos', 'retail', 'Point of sale terminals', '["Windows 10 IoT", "Android POS", "Linux POS"]', '{"ethernet": "required", "wifi": "backup", "cellular": "backup"}', '["payment_encryption", "pci_compliance", "transaction_security"]', '["employee_login", "manager_override", "card_authentication"]', '["payment_integration", "inventory_sync", "staff_training"]', '["transaction_data", "inventory_levels", "performance_metrics"]', '["pci_dss", "payment_regulations"]', '{"ncr": "aloha", "oracle": "micros", "square": "terminal"}', 'high', 'medium'),
('Self-Service Kiosks', 'pos', 'self_service', 'Customer self-service terminals', '["Windows 10", "Android kiosk", "Custom embedded"]', '{"ethernet": "preferred", "wifi": "acceptable"}', '["transaction_security", "customer_privacy", "tamper_detection"]', '["customer_identification", "payment_authentication"]', '["kiosk_configuration", "payment_setup", "accessibility_compliance"]', '["usage_analytics", "transaction_success", "uptime_monitoring"]', '["accessibility_standards", "payment_compliance"]', '{"diebold": "nixdorf", "ncr": "selfserv", "kiosk": "group"}', 'medium', 'medium'),
('Mobile Payment Devices', 'pos', 'mobile', 'Portable payment terminals', '["Payment OS", "Android mobile"]', '{"cellular": "required", "wifi": "backup", "bluetooth": "optional"}', '["payment_encryption", "device_authentication", "transaction_integrity"]', '["merchant_login", "device_pairing", "payment_authentication"]', '["device_provisioning", "payment_testing", "merchant_training"]', '["transaction_volume", "device_location", "battery_status"]', '["pci_mobile", "payment_regulations"]', '{"square": "reader", "stripe": "terminal", "clover": "flex"}', 'high', 'low'),

-- Digital Signage
('Display Controllers', 'signage', 'display', 'Digital signage display controllers', '["Android signage", "Windows 10 IoT", "Linux embedded"]', '{"ethernet": "preferred", "wifi": "acceptable"}', '["content_security", "remote_management", "tamper_protection"]', '["admin_authentication", "content_approval", "device_registration"]', '["display_calibration", "content_scheduling", "remote_deployment"]', '["display_status", "content_analytics", "performance_monitoring"]', '["content_regulations", "accessibility_standards"]', '{"brightsign": "os", "samsung": "tizen", "lg": "webos"}', 'low', 'low'),
('Interactive Displays', 'signage', 'interactive', 'Touch-enabled interactive displays', '["Android touch", "Windows touch", "Custom interactive OS"]', '{"ethernet": "required", "wifi": "optional", "high_bandwidth": "preferred"}', '["user_interaction_logging", "content_protection", "session_management"]', '["user_authentication", "content_access_control"]', '["touch_calibration", "content_integration", "accessibility_setup"]', '["interaction_analytics", "session_data", "display_health"]', '["accessibility_compliance", "user_privacy"]', '{"smart": "notebook", "promethean": "activpanel", "viewsonic": "viewboard"}', 'medium', 'medium'),
('Video Walls', 'signage', 'video_wall', 'Multi-display video wall systems', '["Video wall OS", "Matrix switching firmware"]', '{"ethernet": "required", "high_bandwidth": "required", "redundant": "recommended"}', '["content_distribution", "display_synchronization", "redundancy"]', '["operator_authentication", "content_scheduling", "administrative_access"]', '["display_alignment", "color_calibration", "content_distribution_setup"]', '["display_uniformity", "content_performance", "system_health"]', '["content_standards", "broadcasting_regulations"]', '{"christie": "pandoras_box", "datapath": "visionsc", "matrox": "mura"}', 'medium', 'high'),

-- Specialized Devices
('Barcode Scanners', 'specialized', 'data_capture', 'Handheld and fixed barcode scanners', '["Scanner firmware", "Android enterprise"]', '{"wireless": "preferred", "ethernet": "backup", "bluetooth": "optional"}', '["data_encryption", "device_authentication", "audit_logging"]', '["worker_authentication", "device_pairing", "app_authentication"]', '["application_integration", "barcode_setup", "worker_training"]', '["scan_accuracy", "battery_life", "productivity_metrics"]', '["data_privacy", "inventory_regulations"]', '{"zebra": "emdk", "honeywell": "mobility_edge", "datalogic": "memor"}', 'low', 'low'),
('RFID Readers', 'specialized', 'data_capture', 'Radio frequency identification readers', '["RFID firmware", "Reader OS"]', '{"ethernet": "required", "rs232": "backup"}', '["rf_security", "tag_authentication", "data_integrity"]', '["reader_authentication", "application_authentication"]', '["rf_calibration", "tag_commissioning", "integration_testing"]', '["read_rates", "tag_performance", "rf_environment"]', '["privacy_regulations", "rf_compliance"]', '{"impinj": "speedway", "zebra": "fx9600", "honeywell": "thor"}', 'medium', 'medium'),
('Environmental Sensors', 'specialized', 'monitoring', 'Temperature, humidity, air quality sensors', '["Sensor firmware", "IoT OS"]', '{"wireless": "preferred", "low_power": "required"}', '["data_encryption", "sensor_authentication", "tamper_detection"]', '["device_authentication", "network_authentication"]', '["sensor_placement", "calibration", "baseline_establishment"]', '["environmental_data", "sensor_health", "alert_management"]', '["environmental_regulations", "safety_standards"]', '{"sensirion": "environmental", "bosch": "bme", "honeywell": "sensing"}', 'low', 'low');

-- Create deployment phases library
CREATE TABLE IF NOT EXISTS public.deployment_phases_library (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  name text NOT NULL,
  phase_order integer NOT NULL DEFAULT 1,
  description text,
  typical_duration text,
  prerequisites jsonb DEFAULT '[]'::jsonb,
  deliverables jsonb DEFAULT '[]'::jsonb,
  success_criteria jsonb DEFAULT '[]'::jsonb,
  stakeholders jsonb DEFAULT '[]'::jsonb,
  activities jsonb DEFAULT '[]'::jsonb,
  risks jsonb DEFAULT '[]'::jsonb,
  tools_required jsonb DEFAULT '[]'::jsonb,
  documentation_templates jsonb DEFAULT '[]'::jsonb,
  quality_gates jsonb DEFAULT '[]'::jsonb,
  rollback_procedures jsonb DEFAULT '[]'::jsonb,
  communication_plan jsonb DEFAULT '[]'::jsonb,
  resource_requirements jsonb DEFAULT '[]'::jsonb,
  compliance_checkpoints jsonb DEFAULT '[]'::jsonb,
  automation_opportunities jsonb DEFAULT '[]'::jsonb,
  lessons_learned jsonb DEFAULT '[]'::jsonb,
  phase_type text DEFAULT 'standard',
  complexity_level text DEFAULT 'medium',
  is_mandatory boolean DEFAULT true,
  is_active boolean DEFAULT true,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now()
);

-- Enable RLS on deployment_phases_library
ALTER TABLE public.deployment_phases_library ENABLE ROW LEVEL SECURITY;

-- Create RLS policies for deployment_phases_library
CREATE POLICY "Resource library readable by authenticated users" ON public.deployment_phases_library
  FOR SELECT USING (true);

CREATE POLICY "Users can create deployment phases" ON public.deployment_phases_library
  FOR INSERT WITH CHECK (true);

CREATE POLICY "Users can update deployment phases" ON public.deployment_phases_library
  FOR UPDATE USING (true);

-- Add trigger for updated_at
CREATE TRIGGER update_deployment_phases_library_updated_at
  BEFORE UPDATE ON public.deployment_phases_library
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();

-- Insert comprehensive deployment phases
INSERT INTO deployment_phases_library (name, phase_order, description, typical_duration, prerequisites, deliverables, success_criteria, stakeholders, activities, risks, tools_required, documentation_templates, quality_gates, rollback_procedures, communication_plan, resource_requirements, compliance_checkpoints, automation_opportunities, lessons_learned, phase_type, complexity_level, is_mandatory) VALUES
('Project Initiation', 1, 'Project charter, stakeholder identification, and initial planning', '2-4 weeks', '["business_case_approved", "budget_allocated", "sponsor_identified"]', '["project_charter", "stakeholder_register", "initial_timeline", "risk_register"]', '["charter_approved", "stakeholders_identified", "budget_confirmed", "timeline_agreed"]', '["project_sponsor", "business_stakeholders", "it_leadership", "security_team"]', '["charter_creation", "stakeholder_mapping", "risk_identification", "success_criteria_definition"]', '["scope_creep", "stakeholder_misalignment", "budget_constraints", "timeline_pressure"]', '["project_management_software", "collaboration_tools", "documentation_platform"]', '["project_charter_template", "stakeholder_register_template", "risk_register_template"]', '["charter_approval", "stakeholder_signoff", "budget_confirmation"]', '["project_cancellation", "scope_reduction", "timeline_extension"]', '["kickoff_meeting", "stakeholder_updates", "sponsor_reports"]', '["project_manager", "business_analyst", "architect"]', '["governance_framework", "risk_management", "change_control"]', '["charter_automation", "stakeholder_mapping_tools"]', '["clear_success_criteria", "stakeholder_engagement", "early_risk_identification"]', 'planning', 'medium', true),

('Requirements Gathering', 2, 'Detailed business and technical requirements collection', '3-6 weeks', '["project_charter_approved", "stakeholders_identified", "access_to_smEs"]', '["business_requirements", "technical_requirements", "functional_specifications", "non_functional_requirements"]', '["requirements_documented", "stakeholder_approval", "requirements_traceability", "gap_analysis_complete"]', '["business_users", "technical_teams", "security_team", "compliance_team"]', '["interviews", "workshops", "documentation_review", "gap_analysis", "requirements_validation"]', '["incomplete_requirements", "changing_requirements", "stakeholder_availability", "legacy_system_constraints"]', '["requirements_management_tool", "collaboration_software", "documentation_platform", "gap_analysis_tools"]', '["requirements_template", "interview_guide", "workshop_template", "gap_analysis_template"]', '["requirements_review", "stakeholder_approval", "technical_feasibility"]', '["requirements_simplification", "phased_approach", "alternative_solutions"]', '["requirements_sessions", "validation_meetings", "approval_process"]', '["business_analyst", "subject_matter_experts", "technical_architect"]', '["requirements_standards", "documentation_governance"]', '["requirements_automation", "template_generation"]', '["stakeholder_involvement", "iterative_validation", "requirements_prioritization"]', 'planning', 'high', true),

('Architecture Design', 3, 'Technical architecture and solution design', '4-8 weeks', '["requirements_approved", "technical_constraints_identified", "security_requirements_defined"]', '["solution_architecture", "technical_design", "security_architecture", "integration_design"]', '["architecture_approved", "design_standards_met", "security_validated", "scalability_confirmed"]', '["solution_architect", "security_architect", "infrastructure_team", "network_team"]', '["architecture_design", "security_design", "integration_planning", "performance_modeling"]', '["architectural_complexity", "integration_challenges", "security_gaps", "performance_issues"]', '["architecture_tools", "modeling_software", "security_tools", "performance_testing_tools"]', '["architecture_template", "security_design_template", "integration_template"]', '["architecture_review", "security_review", "performance_validation"]', '["architecture_simplification", "alternative_designs", "incremental_approach"]', '["design_reviews", "stakeholder_presentations", "approval_meetings"]', '["solution_architect", "security_architect", "technical_leads"]', '["architecture_standards", "security_compliance", "integration_governance"]', '["design_automation", "template_generation", "validation_tools"]', '["modular_design", "security_by_design", "performance_considerations"]', 'design', 'high', true),

('Environment Setup', 4, 'Infrastructure and environment preparation', '2-4 weeks', '["architecture_approved", "infrastructure_requirements_defined", "access_permissions_granted"]', '["development_environment", "testing_environment", "production_environment", "deployment_tools"]', '["environments_operational", "connectivity_verified", "security_implemented", "monitoring_active"]', '["infrastructure_team", "network_team", "security_team", "operations_team"]', '["server_provisioning", "network_configuration", "security_hardening", "monitoring_setup"]', '["infrastructure_delays", "connectivity_issues", "security_vulnerabilities", "capacity_constraints"]', '["infrastructure_automation", "configuration_management", "monitoring_tools", "security_scanners"]', '["environment_setup_guide", "configuration_templates", "security_checklists"]', '["environment_validation", "security_scan", "performance_baseline"]', '["environment_rebuild", "configuration_rollback", "alternative_infrastructure"]', '["infrastructure_updates", "team_notifications", "status_reports"]', '["infrastructure_engineers", "network_engineers", "security_engineers"]', '["infrastructure_standards", "security_baseline", "monitoring_requirements"]', '["infrastructure_as_code", "automated_provisioning", "configuration_automation"]', '["automation_first", "security_hardening", "comprehensive_monitoring"]', 'preparation', 'medium', true),

('Development Phase', 5, 'Solution development and configuration', '8-16 weeks', '["environments_ready", "development_team_onboarded", "coding_standards_defined"]', '["application_code", "configuration_scripts", "integration_components", "unit_tests"]', '["code_quality_met", "unit_tests_passing", "security_scans_clean", "documentation_complete"]', '["development_team", "technical_leads", "quality_assurance", "security_team"]', '["coding", "configuration", "integration_development", "unit_testing", "code_reviews"]', '["technical_debt", "integration_complexity", "security_vulnerabilities", "performance_issues"]', '["development_tools", "version_control", "ci_cd_pipeline", "code_quality_tools"]', '["coding_standards", "review_templates", "testing_templates", "documentation_templates"]', '["code_review", "quality_gates", "security_scan", "unit_test_coverage"]', '["code_rollback", "feature_removal", "alternative_implementation"]', '["development_updates", "milestone_reports", "issue_escalation"]', '["developers", "technical_leads", "qa_engineers"]', '["coding_standards", "security_guidelines", "quality_requirements"]', '["automated_testing", "continuous_integration", "code_generation"]', '["clean_code", "security_first", "comprehensive_testing"]', 'development', 'high', true),

('Integration Testing', 6, 'System integration and interface testing', '3-6 weeks', '["development_complete", "test_environments_ready", "test_data_prepared"]', '["integration_test_results", "interface_validation", "performance_test_results", "security_test_results"]', '["integration_tests_passing", "performance_acceptable", "security_validated", "interfaces_functional"]', '["qa_team", "integration_team", "performance_team", "security_team"]', '["integration_testing", "interface_testing", "performance_testing", "security_testing"]', '["integration_failures", "performance_bottlenecks", "security_vulnerabilities", "data_inconsistencies"]', '["testing_frameworks", "performance_tools", "security_scanners", "monitoring_tools"]', '["test_plan_template", "test_case_template", "defect_template", "test_report_template"]', '["test_completion", "defect_resolution", "performance_validation", "security_clearance"]', '["test_scope_reduction", "performance_optimization", "security_remediation"]', '["test_progress", "defect_status", "milestone_updates"]', '["qa_engineers", "performance_engineers", "security_testers"]', '["testing_standards", "performance_criteria", "security_requirements"]', '["automated_testing", "continuous_testing", "test_data_management"]', '["early_testing", "comprehensive_coverage", "automated_regression"]', 'testing', 'high', true),

('User Acceptance Testing', 7, 'End-user validation and acceptance', '2-4 weeks', '["integration_testing_complete", "user_training_complete", "production_like_environment"]', '["uat_test_results", "user_feedback", "acceptance_criteria_validation", "training_effectiveness"]', '["user_acceptance_achieved", "business_requirements_met", "usability_validated", "training_effective"]', '["business_users", "end_users", "training_team", "support_team"]', '["user_acceptance_testing", "usability_testing", "training_validation", "feedback_collection"]', '["user_resistance", "usability_issues", "training_gaps", "acceptance_delays"]', '["uat_tools", "feedback_collection", "training_platforms", "collaboration_tools"]', '["uat_plan_template", "test_scenario_template", "feedback_template", "acceptance_template"]', '["uat_completion", "user_signoff", "training_validation", "go_live_readiness"]', '["additional_training", "usability_improvements", "scope_adjustment"]', '["uat_progress", "user_feedback", "acceptance_status"]', '["business_users", "trainers", "change_management_team"]', '["acceptance_criteria", "usability_standards", "training_requirements"]', '["automated_uat", "feedback_automation", "training_analytics"]', '["user_involvement", "iterative_feedback", "comprehensive_training"]', 'validation', 'medium', true),

('Production Deployment', 8, 'Go-live and production deployment', '1-2 weeks', '["uat_passed", "production_environment_ready", "deployment_plan_approved", "rollback_plan_ready"]', '["production_deployment", "go_live_validation", "performance_monitoring", "support_readiness"]', '["successful_deployment", "system_operational", "performance_acceptable", "users_productive"]', '["deployment_team", "operations_team", "support_team", "business_teams"]', '["production_deployment", "smoke_testing", "performance_monitoring", "user_support"]', '["deployment_failures", "performance_issues", "user_adoption_problems", "support_overload"]', '["deployment_tools", "monitoring_systems", "support_tools", "communication_platforms"]', '["deployment_plan", "go_live_checklist", "support_procedures", "communication_plan"]', '["deployment_validation", "performance_check", "user_feedback", "support_metrics"]', '["immediate_rollback", "hotfixes", "performance_tuning", "additional_support"]', '["go_live_communication", "status_updates", "issue_escalation"]', '["deployment_engineers", "operations_team", "support_staff"]', '["deployment_standards", "operational_procedures", "support_standards"]', '["automated_deployment", "infrastructure_automation", "monitoring_automation"]', '["thorough_testing", "gradual_rollout", "comprehensive_monitoring"]', 'deployment', 'high', true),

('Post-Deployment Support', 9, 'Stabilization and hypercare support', '4-8 weeks', '["production_deployed", "support_team_ready", "monitoring_active", "escalation_procedures_defined"]', '["stabilized_system", "resolved_issues", "performance_optimization", "user_adoption_metrics"]', '["system_stable", "issues_resolved", "performance_optimized", "users_satisfied"]', '["support_team", "operations_team", "development_team", "business_users"]', '["issue_resolution", "performance_tuning", "user_support", "system_monitoring"]', '["system_instability", "performance_degradation", "user_resistance", "support_overload"]', '["support_tools", "monitoring_systems", "performance_tools", "communication_platforms"]', '["support_procedures", "escalation_matrix", "performance_reports", "issue_tracking"]', '["stability_achieved", "performance_acceptable", "support_effective", "user_satisfaction"]', '["emergency_fixes", "performance_optimization", "additional_training", "process_improvement"]', '["support_updates", "performance_reports", "user_feedback"]', '["support_engineers", "operations_staff", "subject_matter_experts"]', '["support_standards", "sla_requirements", "escalation_procedures"]', '["automated_monitoring", "self_healing", "predictive_analytics"]', '["proactive_monitoring", "rapid_response", "continuous_improvement"]', 'support', 'medium', true),

('Project Closure', 10, 'Project wrap-up and knowledge transfer', '2-3 weeks', '["system_stabilized", "handover_complete", "documentation_finalized", "lessons_learned_captured"]', '["project_closure_report", "lessons_learned", "knowledge_transfer", "resource_release"]', '["project_officially_closed", "knowledge_transferred", "resources_released", "lessons_documented"]', '["project_manager", "team_leads", "operations_team", "business_stakeholders"]', '["project_review", "knowledge_transfer", "documentation_finalization", "resource_transition"]', '["incomplete_handover", "knowledge_loss", "resource_conflicts", "unresolved_issues"]', '["documentation_tools", "knowledge_management", "project_reporting", "resource_management"]', '["closure_report_template", "lessons_learned_template", "handover_checklist", "knowledge_base"]', '["handover_completion", "documentation_review", "stakeholder_approval", "resource_confirmation"]', '["extended_support", "additional_documentation", "delayed_closure"]', '["closure_communication", "final_reports", "stakeholder_notifications"]', '["project_manager", "knowledge_managers", "operations_leads"]', '["closure_standards", "knowledge_management", "resource_governance"]', '["automated_reporting", "knowledge_capture", "resource_tracking"]', '["thorough_documentation", "comprehensive_handover", "continuous_learning"]', 'closure', 'low', true);