// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jzqzykxihtpqnoppxodg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp6cXp5a3hpaHRwcW5vcHB4b2RnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyOTM3MjIsImV4cCI6MjA2ODg2OTcyMn0.0M-9qdvqgQslIkVSrfAcwHCHRH2s3cw4ikpbFXSHyYc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});